bin: Shell format ;

diff --git a/bin/7z-fromzip b/bin/7z-fromzip
--- a/bin/7z-fromzip
+++ b/bin/7z-fromzip
@@ -1,31 +1,34 @@
 #!/bin/bash
 export HAM_NO_VER_CHECK=1
-if [[ -z "$HAM_HOME" ]]; then echo "E/HAM_HOME not set !"; exit 1; fi
+if [[ -z "$HAM_HOME" ]]; then
+  echo "E/HAM_HOME not set !"
+  exit 1
+fi
 . "$HAM_HOME/bin/ham-bash-setenv.sh"
 
-CWD=`pwd`
+CWD=$(pwd)
 
 ARCH="$CWD/$1"
 if [ ! -f "$ARCH" ]; then
-    ARCH="$1"
-    if [ ! -f "$ARCH" ]; then
-        echo "Can't find input archive '$ARCH' !"
-        echo "syntax: 7z-fromzip ARCHIVE PASSWORD"
-        exit -1
-    fi
+  ARCH="$1"
+  if [ ! -f "$ARCH" ]; then
+    echo "Can't find input archive '$ARCH' !"
+    echo "syntax: 7z-fromzip ARCHIVE PASSWORD"
+    exit -1
+  fi
 fi
 
 DEST="${ARCH%.*}.7z"
 echo "I/Converting '$ARCH' to '$DEST'."
 if [[ -e $DEST ]]; then
-    echo "Output archive '$DEST' already exist !"
-    exit -1
+  echo "Output archive '$DEST' already exist !"
+  exit -1
 fi
 
 PASSWORD="$2"
 
 # Make the temporary extraction directory
-TMP_DIR=$HOME/_ham/_tmp_ext_`basename $ARCH`
+TMP_DIR=$HOME/_ham/_tmp_ext_$(basename $ARCH)
 mkdir -p $TMP_DIR
 errcheck $? ham "Can't create the temporary directory '$TMP_DIR'."
 
@@ -33,22 +36,22 @@ errcheck $? ham "Can't create the temporary directory '$TMP_DIR'."
 cd $TMP_DIR
 echo "I/Extracting zip file..."
 if [[ "$PASSWORD" == "" ]]; then
-    echo "I/7z -y x $ARCH"
-    7z -y x "$ARCH"
+  echo "I/7z -y x $ARCH"
+  7z -y x "$ARCH"
 else
-    echo "I/7z -p$PASSWORD -y x $ARCH"
-    7z -p$PASSWORD -y x "$ARCH"
+  echo "I/7z -p$PASSWORD -y x $ARCH"
+  7z -p$PASSWORD -y x "$ARCH"
 fi
 errcheck $? ham "Can't extract the zip file '$ARCH'."
 
 # Packing the 7z archive
 echo "I/Packing 7zfile..."
 if [[ $PASSWORD == "" ]]; then
-    echo "I/7z a -mx=6 -ms=on -mhc=on -mtc=off ."
-    7z a -t7z "$DEST" -mx=6 -ms=on -mhc=on -mtc=off .
+  echo "I/7z a -mx=6 -ms=on -mhc=on -mtc=off ."
+  7z a -t7z "$DEST" -mx=6 -ms=on -mhc=on -mtc=off .
 else
-    echo "I/7z a -mx=6 -ms=on -mhc=on -mtc=off -p$PASSWORD ."
-    7z a -t7z "$DEST" -mx=6 -ms=on -mhc=on -mtc=off -p$PASSWORD .
+  echo "I/7z a -mx=6 -ms=on -mhc=on -mtc=off -p$PASSWORD ."
+  7z a -t7z "$DEST" -mx=6 -ms=on -mhc=on -mtc=off -p$PASSWORD .
 fi
 errcheck $? ham "Can't pack the 7z file '$ARCH'."
 
diff --git a/bin/ham b/bin/ham
--- a/bin/ham
+++ b/bin/ham
@@ -2,69 +2,68 @@
 EXEC_TIME="$(date +%s)"
 PREV_PATH=${PATH}
 if [[ -z "$HAM_HOME" ]]; then
-    export HAM_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
-    echo "W/HAM_HOME not set, set to:" $HAM_HOME
+  export HAM_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
+  echo "W/HAM_HOME not set, set to:" $HAM_HOME
 fi
 . "$HAM_HOME/bin/ham-bash-setenv.sh"
 export PATH=${PREV_PATH}:${PATH}
 
 # the help
 usage() {
-    echo "usage: ham [ options ] targets|scripts..."
-    echo "version:" `"${HAM_CMD}" -v`
-    echo ""
-    echo "ham launch script:"
-    echo "  -h             This help message"
-    echo "  -v             Print ham's executable version"
-    echo "  -X toolkit     Import a toolkit's _ham_project and build it."
-    echo "                 (equivalent to '-T toolkit -D toolkit')."
-    echo "  -D toolkit     Add a toolkit to build - the toolkit should be in $WORK"
-    echo "                 (can be specified multiple times)"
-    echo "  -T toolset     Add a toolset to import"
-    echo "                 (can be specified multiple times)"
-    echo "  -E env=value   Add an envvar to set."
-    echo "  --             Following parameters will be passed to ham directly"
-    echo ""
-    echo "ham process:"
-    "${HAM_CMD}" -? | grep "^[- ]"
-    echo ""
-    echo "example:"
-    echo "  # Make all in the niLang & Vlk toolkits with the current toolsets."
-    echo "  ham -D niLang -D Vlk all"
-    echo "  # Run _build_bootstrap.sh in the niLang toolkit with the current toolsets."
-    echo "  ham -D niLang _build_bootstrap.sh"
-    echo "  # Make niLang for the web-js build target with the niLang toolsets."
-    echo "  BUILD_TARGET=web-js ham -X niLang pass1 all"
-    echo "  # Make the debug version of niLang for the web-js build target with the niLang toolsets"
-    echo "  BUILD_TARGET=web-js BUILD=da ham -X niLang pass1 all"
-    echo "  # Make the release build (ra) of the current toolkit. BUILD=ra is the default if not specified."
-    echo "  ham BUILD=ra all"
-    echo "  # Make all in the current toolkit, displaying all the commands."
-    echo "  ham -- -dx all"
-    echo ""
+  echo "usage: ham [ options ] targets|scripts..."
+  echo "version:" $("${HAM_CMD}" -v)
+  echo ""
+  echo "ham launch script:"
+  echo "  -h             This help message"
+  echo "  -v             Print ham's executable version"
+  echo "  -X toolkit     Import a toolkit's _ham_project and build it."
+  echo "                 (equivalent to '-T toolkit -D toolkit')."
+  echo "  -D toolkit     Add a toolkit to build - the toolkit should be in $WORK"
+  echo "                 (can be specified multiple times)"
+  echo "  -T toolset     Add a toolset to import"
+  echo "                 (can be specified multiple times)"
+  echo "  -E env=value   Add an envvar to set."
+  echo "  --             Following parameters will be passed to ham directly"
+  echo ""
+  echo "ham process:"
+  "${HAM_CMD}" -? | grep "^[- ]"
+  echo ""
+  echo "example:"
+  echo "  # Make all in the niLang & Vlk toolkits with the current toolsets."
+  echo "  ham -D niLang -D Vlk all"
+  echo "  # Run _build_bootstrap.sh in the niLang toolkit with the current toolsets."
+  echo "  ham -D niLang _build_bootstrap.sh"
+  echo "  # Make niLang for the web-js build target with the niLang toolsets."
+  echo "  BUILD_TARGET=web-js ham -X niLang pass1 all"
+  echo "  # Make the debug version of niLang for the web-js build target with the niLang toolsets"
+  echo "  BUILD_TARGET=web-js BUILD=da ham -X niLang pass1 all"
+  echo "  # Make the release build (ra) of the current toolkit. BUILD=ra is the default if not specified."
+  echo "  ham BUILD=ra all"
+  echo "  # Make all in the current toolkit, displaying all the commands."
+  echo "  ham -- -dx all"
+  echo ""
 
-    if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
-        # sourced...
-        return 1
-    else
-        # regular call
-        exit 1
-    fi
+  if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
+    # sourced...
+    return 1
+  else
+    # regular call
+    exit 1
+  fi
 }
-
 
 HAM_CMD="$HAM_HOME/bin/$HAM_BIN_LOA/ham"
 if [[ ! -e "$HAM_CMD" ]]; then
-    echo "E/Can't find ham executable '$HAM_CMD'."
-    echo ""
-    usage
+  echo "E/Can't find ham executable '$HAM_CMD'."
+  echo ""
+  usage
 fi
 
 # Check that there is at least one argument...
 if [ $# = 0 ]; then
-    echo "E/No argument specified"
-    echo ""
-    usage
+  echo "E/No argument specified"
+  echo ""
+  usage
 fi
 
 # process the arguments
@@ -73,94 +72,92 @@ _ARG_DIRECTORIES=()
 _ARG_ENVS=()
 
 process_toolset() {
-    OPTARG="$1"
-    _ARG_TOOLSETS+=("$OPTARG")
+  OPTARG="$1"
+  _ARG_TOOLSETS+=("$OPTARG")
 }
 
 process_directory() {
-    OPTARG=`ham-url dec "$1"`
-    if  [[ "$OPTARG" == ?:/* ]] || [[ "$OPTARG" == /* ]] || [[ "$OPTARG" == .* ]] ;
-    then
-        _ARG_DIRECTORY="$OPTARG"
-        if [[ ! -e "$_ARG_DIRECTORY" ]]; then
-            echo "E/Can't find directory '$_ARG_DIRECTORY'"
-            usage
-        fi
-    else
-        # Work App path
-        _ARG_DIRECTORY="$WORK/$OPTARG/"
-        if [[ ! -e "$_ARG_DIRECTORY" ]]; then
-            echo "E/Can't find directory '$_ARG_DIRECTORY'"
-            usage
-        fi
+  OPTARG=$(ham-url dec "$1")
+  if [[ "$OPTARG" == ?:/* ]] || [[ "$OPTARG" == /* ]] || [[ "$OPTARG" == .* ]]; then
+    _ARG_DIRECTORY="$OPTARG"
+    if [[ ! -e "$_ARG_DIRECTORY" ]]; then
+      echo "E/Can't find directory '$_ARG_DIRECTORY'"
+      usage
     fi
-    _ARG_DIRECTORIES+=("$_ARG_DIRECTORY")
+  else
+    # Work App path
+    _ARG_DIRECTORY="$WORK/$OPTARG/"
+    if [[ ! -e "$_ARG_DIRECTORY" ]]; then
+      echo "E/Can't find directory '$_ARG_DIRECTORY'"
+      usage
+    fi
+  fi
+  _ARG_DIRECTORIES+=("$_ARG_DIRECTORY")
 }
 
 process_env() {
-    _ARG_ENVS+=($1)
+  _ARG_ENVS+=($1)
 }
 
-while getopts "T:D:X:E:vh" OPT
-do
-    case "$OPT" in
-        h)
-            echo "I/help"
-            echo ""
-            usage
-            ;;
-        \?)
-            echo "E/Invalid option"
-            echo ""
-            usage
-            ;;
-        v)
-            log_info "HAM_CMD: ${HAM_CMD}"
-            log_info "VERSION: $("$HAM_CMD" -v)"
-            if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
-                return 0
-            else
-                exit 0
-            fi
-            ;;
-        T)
-            process_toolset "$OPTARG"
-            ;;
-        D)
-            process_directory "$OPTARG"
-            ;;
-        X)
-            process_toolset "$OPTARG"
-            process_directory "$OPTARG"
-            ;;
-        E)
-            process_env "$OPTARG"
-            ;;
-        *)
-            echo "E/Unknown option '$OPT'"
-            usage
-            ;;
-    esac
+while getopts "T:D:X:E:vh" OPT; do
+  case "$OPT" in
+    h)
+      echo "I/help"
+      echo ""
+      usage
+      ;;
+    \?)
+      echo "E/Invalid option"
+      echo ""
+      usage
+      ;;
+    v)
+      log_info "HAM_CMD: ${HAM_CMD}"
+      log_info "VERSION: $("$HAM_CMD" -v)"
+      if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
+        return 0
+      else
+        exit 0
+      fi
+      ;;
+    T)
+      process_toolset "$OPTARG"
+      ;;
+    D)
+      process_directory "$OPTARG"
+      ;;
+    X)
+      process_toolset "$OPTARG"
+      process_directory "$OPTARG"
+      ;;
+    E)
+      process_env "$OPTARG"
+      ;;
+    *)
+      echo "E/Unknown option '$OPT'"
+      usage
+      ;;
+  esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
 # echo "_ARG_ENVS: ${_ARG_ENVS[@]}"
 
 if [ "${#_ARG_TOOLSETS[@]}" -gt 0 ]; then
-    . "$HAM_HOME/bin/ham-bash-setenv.sh"
-    export HAM_NO_VER_CHECK=${HAM_NO_VER_CHECK:-1}
-    echo "I/Set toolsets '${_ARG_TOOLSETS[@]}'"
-    # Set envvars
-    for ENV in "${_ARG_ENVS[@]}"; do
-        export "$ENV"
-    done
-    . ham-toolset "${_ARG_TOOLSETS[@]}"
-    errcheck $? ham "Can't setup the '${_ARG_TOOLSETS[@]}' toolset(s)."
+  . "$HAM_HOME/bin/ham-bash-setenv.sh"
+  export HAM_NO_VER_CHECK=${HAM_NO_VER_CHECK:-1}
+  echo "I/Set toolsets '${_ARG_TOOLSETS[@]}'"
+  # Set envvars
+  for ENV in "${_ARG_ENVS[@]}"; do
+    export "$ENV"
+  done
+  . ham-toolset "${_ARG_TOOLSETS[@]}"
+  errcheck $? ham "Can't setup the '${_ARG_TOOLSETS[@]}' toolset(s)."
 fi
 
 if [[ -z "$HAM_TOOLSET" ]]; then
-    echo "E/No toolset set, you can set one with the -T flag or '. ham-toolset' ..."
-    usage
+  echo "E/No toolset set, you can set one with the -T flag or '. ham-toolset' ..."
+  usage
 fi
 
 ham_or_bash() {
@@ -184,71 +181,71 @@ ham_or_bash() {
   # Run ham-validate-targets if there are parameters to pass to it
   HAM_EXEC_DIR="."
   if [ "${#HAM_CMD_PARAMS[@]}" -gt 0 ]; then
-      if [[ ! -f "_build.ham" ]]; then
-        if [[ ! -f "sources/_build.ham" ]]; then
-            log_error "Can't find '_build.ham' and 'sources/_build.ham' in '$(pwd)'."
-            exit 1
-        else
-            HAM_EXEC_DIR="./sources"
-        fi
+    if [[ ! -f "_build.ham" ]]; then
+      if [[ ! -f "sources/_build.ham" ]]; then
+        log_error "Can't find '_build.ham' and 'sources/_build.ham' in '$(pwd)'."
+        exit 1
+      else
+        HAM_EXEC_DIR="./sources"
       fi
+    fi
   fi
 
   # Set envvars
   for ENV in "${_ARG_ENVS[@]}"; do
-      export "$ENV"
+    export "$ENV"
   done
 
   # Execute collected .sh files directly
   for SH_FILE in "${SH_FILES[@]}"; do
-      echo "I/Excuting '${SH_FILE}' in '$(pwd)'."
-      "./$SH_FILE"
-      errcheck $? ham "Script '${SH_FILE}' execution failed in '$(pwd)'."
+    echo "I/Excuting '${SH_FILE}' in '$(pwd)'."
+    "./$SH_FILE"
+    errcheck $? ham "Script '${SH_FILE}' execution failed in '$(pwd)'."
   done
 
   # Run the remaining parameters with $HAM_CMD if there are any
   if [ "${#HAM_CMD_PARAMS[@]}" -gt 0 ]; then
-      if [ -n "$HAM_EXEC_DIR" ]; then
-        cd "$HAM_EXEC_DIR"
-      fi
-      echo "I/'ham ${HAM_CMD_PARAMS[@]}' in '$(pwd)'"
-      case $HAM_OS in
-        NT*)
-          # Disable MSYS2 path translation since ham provides proper windows path
-          # and MSYS2 for some reason mangles absolute paths ('C:/Bla'
-          # becomes 'D:/C:/' - seems like its too hard to check that it has a
-          # drive in the path?)
-          MSYS2_ARG_CONV_EXCL='*' "$HAM_CMD" "${HAM_CMD_PARAMS[@]}"
-          ;;
-        *)
-          "$HAM_CMD" "${HAM_CMD_PARAMS[@]}"
-          ;;
-      esac
-      errcheck $? ham "Ham build in '$DIR' failed."
+    if [ -n "$HAM_EXEC_DIR" ]; then
+      cd "$HAM_EXEC_DIR"
+    fi
+    echo "I/'ham ${HAM_CMD_PARAMS[@]}' in '$(pwd)'"
+    case $HAM_OS in
+      NT*)
+        # Disable MSYS2 path translation since ham provides proper windows path
+        # and MSYS2 for some reason mangles absolute paths ('C:/Bla'
+        # becomes 'D:/C:/' - seems like its too hard to check that it has a
+        # drive in the path?)
+        MSYS2_ARG_CONV_EXCL='*' "$HAM_CMD" "${HAM_CMD_PARAMS[@]}"
+        ;;
+      *)
+        "$HAM_CMD" "${HAM_CMD_PARAMS[@]}"
+        ;;
+    esac
+    errcheck $? ham "Ham build in '$DIR' failed."
   fi
 }
 
 hamIn() {
-    export CWD="`pwd`"
-    export DIR="$1"
-    shift
-    if [[ "$CWD" != "$DIR" ]]; then
-        pushd "$DIR"
-    fi
-    ham_or_bash "$@"
-    errcheck $? ham "Run in '$DIR' failed."
-    if [[ "$CWD" != "$DIR" ]]; then
-        popd > /dev/null
-    fi
+  export CWD="$(pwd)"
+  export DIR="$1"
+  shift
+  if [[ "$CWD" != "$DIR" ]]; then
+    pushd "$DIR"
+  fi
+  ham_or_bash "$@"
+  errcheck $? ham "Run in '$DIR' failed."
+  if [[ "$CWD" != "$DIR" ]]; then
+    popd >/dev/null
+  fi
 }
 
 if [[ "$_ARG_DIRECTORY" != "" ]]; then
-    for dir in "${_ARG_DIRECTORIES[@]}"; do
-        hamIn "$dir" $*
-    done
+  for dir in "${_ARG_DIRECTORIES[@]}"; do
+    hamIn "$dir" $*
+  done
 else
-    hamIn . $*
+  hamIn . $*
 fi
 
-EXEC_TIME="$(($(date +%s)-EXEC_TIME))"
+EXEC_TIME="$(($(date +%s) - EXEC_TIME))"
 echo "...ham ran in ${EXEC_TIME}s..."
diff --git a/bin/ham-gen-compile-commands b/bin/ham-gen-compile-commands
--- a/bin/ham-gen-compile-commands
+++ b/bin/ham-gen-compile-commands
@@ -9,21 +9,21 @@ sed '
 [
 $a\
 }]
-$ d' < $TMP_PATH 1<> $JSON
+$ d' <$TMP_PATH 1<>$JSON
 
 # Get rid of the temp file
 rm $TMP_PATH
 
 # Generate gtags.files, requires global to be installed
 if [ "$1" == gtags ]; then
-    if [ -e "$JSON" ]; then
-        grep '"file"' compile_commands.json | sed 's~.*"file": "~~g' | sed 's~"~~g' > gtags.files
-        if [ ! -e "GTAGS" ]; then
-            gtags
-        fi
-        global -u
-    else
-        echo "$JSON not found."
-        exit 1
+  if [ -e "$JSON" ]; then
+    grep '"file"' compile_commands.json | sed 's~.*"file": "~~g' | sed 's~"~~g' >gtags.files
+    if [ ! -e "GTAGS" ]; then
+      gtags
     fi
+    global -u
+  else
+    echo "$JSON not found."
+    exit 1
+  fi
 fi
diff --git a/bin/ham-install-os-packages b/bin/ham-install-os-packages
--- a/bin/ham-install-os-packages
+++ b/bin/ham-install-os-packages
@@ -1,7 +1,7 @@
 #!/bin/bash
 if [[ -z "$HAM_HOME" ]]; then
-    export HAM_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
-    echo "W/HAM_HOME not set, set to:" $HAM_HOME
+  export HAM_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
+  echo "W/HAM_HOME not set, set to:" $HAM_HOME
 fi
 . "$HAM_HOME/bin/ham-bash-setenv.sh"
 
@@ -10,50 +10,52 @@ fi
 TAG="ham-install-os-packages-${HAM_OS}-v23_02_08"
 TAGFILE="$TEMPDIR/ham-install-os-packages-${HAM_OS}-tag.txt"
 
-if [[ `tagfile_status "$TAGFILE" "$TAG"` == "up-to-date" ]]; then
-    echo "I/ham-install-os-packages tagfile is up-to-date."
-    if [ "$1" == "nocheck" ] || [ "$1" == "force" ]; then
-        echo "I/Installing anyway because of 'nocheck' option."
-    else
-        exit 0
-    fi
+if [[ $(tagfile_status "$TAGFILE" "$TAG") == "up-to-date" ]]; then
+  echo "I/ham-install-os-packages tagfile is up-to-date."
+  if [ "$1" == "nocheck" ] || [ "$1" == "force" ]; then
+    echo "I/Installing anyway because of 'nocheck' option."
+  else
+    exit 0
+  fi
 else
-    echo "I/HAM_HOME: ${HAM_HOME}"
-    echo "I/TAGFILE: ${TAGFILE}"
-    echo "I/ham-install-os-packages tagfile is outdated, installing os packages..."
+  echo "I/HAM_HOME: ${HAM_HOME}"
+  echo "I/TAGFILE: ${TAGFILE}"
+  echo "I/ham-install-os-packages tagfile is outdated, installing os packages..."
 fi
 
 case $HAM_OS in
-    NT*)
-        echo "### No extra packages need to be installed on Windows ###"
-        ;;
-    OSX)
-        echo "### Make sure "$HAM_HOME/bin" isn't quarantined ###"
-        toolset_unquarantine_dir "$HAM_HOME/bin"
-        echo "### Installing packages required by ham on OSX (brew) ###"
-        # coreutils is mainly for 'realpath' atm
-        ham-brew install jq yq wget hstr mc ncdu htop coreutils
-        ;;
-    LINUX)
-        if [ $(type apt-get 2>/dev/null | wc -l) = 1 ]; then
-            echo "### Installing packages required by ham on Linux (apt-get) ###"
-            echo "I/Installing apt-get packages"
-            (set -ex ;
-             # autoremove & update fix "E: Unable to correct problems, you have held broken packages."
-             sudo apt -y autoremove ;
-             sudo apt -y update ;
-             # sudo apt -y upgrade ; # Try this if your install seems broken...
-             # install all our required packages
-             sudo NEEDRESTART_MODE=a apt-get -y install software-properties-common build-essential clang lld curl ffmpeg file freeglut3-dev git g++ gcc git htop jq libcurl4-openssl-dev libdw-dev libunwind-dev libsdl2-dev libssl-dev libudev-dev mc mesa-common-dev mesa-utils net-tools ntpdate p7zip-full procps pkg-config python3 python3-pip subversion wget xsltproc)
-        else
-            echo "E/Unsupported LINUX package manager"
-            return 1
-        fi
-        ;;
-    *)
-        echo "E/Toolset: Unsupported host OS"
-        return 1
-        ;;
+  NT*)
+    echo "### No extra packages need to be installed on Windows ###"
+    ;;
+  OSX)
+    echo "### Make sure "$HAM_HOME/bin" isn't quarantined ###"
+    toolset_unquarantine_dir "$HAM_HOME/bin"
+    echo "### Installing packages required by ham on OSX (brew) ###"
+    # coreutils is mainly for 'realpath' atm
+    ham-brew install jq yq wget hstr mc ncdu htop coreutils
+    ;;
+  LINUX)
+    if [ $(type apt-get 2>/dev/null | wc -l) = 1 ]; then
+      echo "### Installing packages required by ham on Linux (apt-get) ###"
+      echo "I/Installing apt-get packages"
+      (
+        set -ex
+        # autoremove & update fix "E: Unable to correct problems, you have held broken packages."
+        sudo apt -y autoremove
+        sudo apt -y update
+        # sudo apt -y upgrade ; # Try this if your install seems broken...
+        # install all our required packages
+        sudo NEEDRESTART_MODE=a apt-get -y install software-properties-common build-essential clang lld curl ffmpeg file freeglut3-dev git g++ gcc git htop jq libcurl4-openssl-dev libdw-dev libunwind-dev libsdl2-dev libssl-dev libudev-dev mc mesa-common-dev mesa-utils net-tools ntpdate p7zip-full procps pkg-config python3 python3-pip subversion wget xsltproc
+      )
+    else
+      echo "E/Unsupported LINUX package manager"
+      return 1
+    fi
+    ;;
+  *)
+    echo "E/Toolset: Unsupported host OS"
+    return 1
+    ;;
 esac
 
 # Update tag file
diff --git a/bin/ham-ls-targets b/bin/ham-ls-targets
--- a/bin/ham-ls-targets
+++ b/bin/ham-ls-targets
@@ -1,60 +1,60 @@
 #!/bin/bash
 if [[ -z "$HAM_HOME" ]]; then
-    export HAM_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
-    echo "W/HAM_HOME not set, set to:" $HAM_HOME
+  export HAM_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
+  echo "W/HAM_HOME not set, set to:" $HAM_HOME
 fi
 . "$HAM_HOME/bin/ham-bash-setenv.sh"
 export PATH=${PREV_PATH}:${PATH}
 
 # the help
 usage() {
-    echo "usage: ham-ls-targets (options) filter"
-    echo ""
-    echo "flags:"
-    echo "  -h             This help message"
-    echo "  -v             Print ham's version"
-    echo "  -t target      Add a target to pass to ham. (if none specified: all runnable)"
-    echo "  -T toolset     Add a toolset to import"
-    echo "                 (can be specified multiple times)"
-    echo "  -D directory   Add a toolkit to build - the toolkit should be in $WORK"
-    echo "                 (can be specified multiple times)"
-    echo "  -b             Only includes the targets that are not up to date."
-    echo ""
-    echo "filter:"
-    echo "  all            List all targets."
-    echo "  no_file        List targets that don't look like a file. (default)"
-    echo "  run            List all targets that look like they can be ran."
-    echo "  debug          List all targets that look like they can be debugged."
-    echo "  test           List all targets that look like a test."
-    echo "  raw_all        Shows the ham output directly."
-    echo "  raw_tu         Shows the ham output of the touched & update targets."
-    echo ""
-    echo "example:"
-    echo "  # List all targets that don't look like a file."
-    echo "  ham-ls-targets no_file"
-    echo "  # List all targets that need to be built and that don't look like a file."
-    echo "  ham-ls-targets -b no_file"
-    echo "  # List all runnable targets"
-    echo "  ham-ls-targets run"
-    echo "  # List all the targets in niLang that dont look like a file"
-    echo "  ham-ls-targets -D niLang no_file"
-    echo "  # List all the targets in niLang"
-    echo "  ham-ls-targets -D niLang all"
-    echo "  # List all the tests in niLang"
-    echo "  ham-ls-targets -D niLang test"
-    echo "  # List all the runnable targets in niLang"
-    echo "  ham-ls-targets -D niLang run"
-    echo "  # List all the niScript targets"
-    echo "  ham-ls-targets -D niLang -t niScript all"
-    echo ""
-    exit 1
+  echo "usage: ham-ls-targets (options) filter"
+  echo ""
+  echo "flags:"
+  echo "  -h             This help message"
+  echo "  -v             Print ham's version"
+  echo "  -t target      Add a target to pass to ham. (if none specified: all runnable)"
+  echo "  -T toolset     Add a toolset to import"
+  echo "                 (can be specified multiple times)"
+  echo "  -D directory   Add a toolkit to build - the toolkit should be in $WORK"
+  echo "                 (can be specified multiple times)"
+  echo "  -b             Only includes the targets that are not up to date."
+  echo ""
+  echo "filter:"
+  echo "  all            List all targets."
+  echo "  no_file        List targets that don't look like a file. (default)"
+  echo "  run            List all targets that look like they can be ran."
+  echo "  debug          List all targets that look like they can be debugged."
+  echo "  test           List all targets that look like a test."
+  echo "  raw_all        Shows the ham output directly."
+  echo "  raw_tu         Shows the ham output of the touched & update targets."
+  echo ""
+  echo "example:"
+  echo "  # List all targets that don't look like a file."
+  echo "  ham-ls-targets no_file"
+  echo "  # List all targets that need to be built and that don't look like a file."
+  echo "  ham-ls-targets -b no_file"
+  echo "  # List all runnable targets"
+  echo "  ham-ls-targets run"
+  echo "  # List all the targets in niLang that dont look like a file"
+  echo "  ham-ls-targets -D niLang no_file"
+  echo "  # List all the targets in niLang"
+  echo "  ham-ls-targets -D niLang all"
+  echo "  # List all the tests in niLang"
+  echo "  ham-ls-targets -D niLang test"
+  echo "  # List all the runnable targets in niLang"
+  echo "  ham-ls-targets -D niLang run"
+  echo "  # List all the niScript targets"
+  echo "  ham-ls-targets -D niLang -t niScript all"
+  echo ""
+  exit 1
 }
 
 HAM_CMD="$HAM_HOME/bin/$HAM_BIN_LOA/ham"
 if [[ ! -e "$HAM_CMD" ]]; then
-    echo "E/Can't find ham executable '$HAM_CMD'."
-    echo ""
-    usage
+  echo "E/Can't find ham executable '$HAM_CMD'."
+  echo ""
+  usage
 fi
 
 # By default we show all targets
@@ -63,67 +63,65 @@ ONLY_TARGETS_THAT_NEED_TO_BE_BUILT=no
 # process the arguments
 TARGETS=()
 _ARG_DIRECTORIES=()
-while getopts "T:D:vbt:" OPT
-do
-    case "$OPT" in
-        h)
-            echo "I/help"
-            echo ""
+while getopts "T:D:vbt:" OPT; do
+  case "$OPT" in
+    h)
+      echo "I/help"
+      echo ""
+      usage
+      ;;
+    \?)
+      echo "E/Invalid option"
+      echo ""
+      usage
+      ;;
+    b)
+      ONLY_TARGETS_THAT_NEED_TO_BE_BUILT=yes
+      ;;
+    v)
+      "$HAM_CMD" -v
+      if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
+        return 0
+      else
+        exit 0
+      fi
+      ;;
+    T)
+      _ARG_TOOLSET="$_ARG_TOOLSET $OPTARG"
+      # echo "_ARG_TOOLSET:" $_ARG_TOOLSET
+      ;;
+    t)
+      TARGETS=(${TARGETS[@]} $OPTARG)
+      # echo "TARGETS:" $TARGETS
+      ;;
+    D)
+      OPTARG=$(ham-url dec "$OPTARG")
+      if [[ "$OPTARG" == ?:/* ]] || [[ "$OPTARG" == /* ]] || [[ "$OPTARG" == .* ]]; then
+        # Explicit path
+        _ARG_DIRECTORY="$OPTARG/sources/"
+        if [[ ! -e "$_ARG_DIRECTORY" ]]; then
+          _ARG_DIRECTORY="$OPTARG"
+          if [[ ! -e "$_ARG_DIRECTORY" ]]; then
+            echo "E/Can't find directory '$_ARG_DIRECTORY'"
             usage
-            ;;
-        \?)
-            echo "E/Invalid option"
-            echo ""
+          fi
+        fi
+      else
+        # Work App path
+        _ARG_DIRECTORY="$WORK/$OPTARG/sources/"
+        if [[ ! -e "$_ARG_DIRECTORY" ]]; then
+          _ARG_DIRECTORY="$WORK/$OPTARG/"
+          if [[ ! -e "$_ARG_DIRECTORY" ]]; then
+            echo "E/Can't find directory '$_ARG_DIRECTORY'"
             usage
-            ;;
-        b)
-          ONLY_TARGETS_THAT_NEED_TO_BE_BUILT=yes
-          ;;
-        v)
-            "$HAM_CMD" -v
-            if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
-                return 0
-            else
-                exit 0
-            fi
-            ;;
-        T)
-            _ARG_TOOLSET="$_ARG_TOOLSET $OPTARG"
-            # echo "_ARG_TOOLSET:" $_ARG_TOOLSET
-            ;;
-        t)
-            TARGETS=(${TARGETS[@]} $OPTARG)
-            # echo "TARGETS:" $TARGETS
-            ;;
-        D)
-            OPTARG=`ham-url dec "$OPTARG"`
-            if  [[ "$OPTARG" == ?:/* ]] || [[ "$OPTARG" == /* ]] || [[ "$OPTARG" == .* ]] ;
-            then
-                # Explicit path
-                _ARG_DIRECTORY="$OPTARG/sources/"
-                if [[ ! -e "$_ARG_DIRECTORY" ]]; then
-                    _ARG_DIRECTORY="$OPTARG"
-                    if [[ ! -e "$_ARG_DIRECTORY" ]]; then
-                        echo "E/Can't find directory '$_ARG_DIRECTORY'"
-                        usage
-                    fi
-                fi
-            else
-                # Work App path
-                _ARG_DIRECTORY="$WORK/$OPTARG/sources/"
-                if [[ ! -e "$_ARG_DIRECTORY" ]]; then
-                    _ARG_DIRECTORY="$WORK/$OPTARG/"
-                    if [[ ! -e "$_ARG_DIRECTORY" ]]; then
-                        echo "E/Can't find directory '$_ARG_DIRECTORY'"
-                        usage
-                    fi
-                fi
-            fi
-            _ARG_DIRECTORIES+=("$_ARG_DIRECTORY")
-            ;;
-    esac
+          fi
+        fi
+      fi
+      _ARG_DIRECTORIES+=("$_ARG_DIRECTORY")
+      ;;
+  esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
 if [ -z "$TARGETS" ]; then
   TARGETS=(all runnable debuggable)
@@ -138,15 +136,15 @@ fi
 shift
 
 if [[ "$_ARG_TOOLSET" != "" ]]; then
-    . "$HAM_HOME/bin/ham-bash-setenv.sh"
-    export HAM_NO_VER_CHECK=${HAM_NO_VER_CHECK:-1}
-    . ham-toolset $_ARG_TOOLSET > /dev/null
-    errcheck $? ham "Can't setup the '$_ARG_TOOLSET' toolset."
+  . "$HAM_HOME/bin/ham-bash-setenv.sh"
+  export HAM_NO_VER_CHECK=${HAM_NO_VER_CHECK:-1}
+  . ham-toolset $_ARG_TOOLSET >/dev/null
+  errcheck $? ham "Can't setup the '$_ARG_TOOLSET' toolset."
 fi
 
 if [[ -z $HAM_TOOLSET ]]; then
-    echo "E/No toolset set, you can set one with the -T flag or '. ham-toolset' ..."
-    usage
+  echo "E/No toolset set, you can set one with the -T flag or '. ham-toolset' ..."
+  usage
 fi
 
 # pierre: We need to wrap the ham call this way otherwise the grep filtering
@@ -170,84 +168,83 @@ filter_get_target_name_and_sort() {
 }
 
 ham_show_targets_in() {
-    export CWD="`pwd`"
-    export DIR="$1"
-    shift
-    if [[ "$CWD" != "$DIR" ]]; then
-        pushd "$DIR" > /dev/null
-    fi
+  export CWD="$(pwd)"
+  export DIR="$1"
+  shift
+  if [[ "$CWD" != "$DIR" ]]; then
+    pushd "$DIR" >/dev/null
+  fi
 
-    HAM_ARGS=(-n -dm)
-    if [ "$ONLY_TARGETS_THAT_NEED_TO_BE_BUILT" != "yes" ]; then
-      HAM_ARGS=(-a ${HAM_ARGS[@]})
-    fi
+  HAM_ARGS=(-n -dm)
+  if [ "$ONLY_TARGETS_THAT_NEED_TO_BE_BUILT" != "yes" ]; then
+    HAM_ARGS=(-a ${HAM_ARGS[@]})
+  fi
 
-    case "$FILTER" in
-      raw_all)
-        ham_call "${HAM_ARGS[@]}" "${TARGETS[@]}"
-        ;;
-      raw_tu)
-        ham_call "${HAM_ARGS[@]}" "${TARGETS[@]}" | grep "touched\|update"
-        ;;
-      all)
-        ham_call "${HAM_ARGS[@]}" "${TARGETS[@]}" |
-          filter_get_buildable_targets |
-          filter_get_target_name_and_sort
-        ;;
-      no_file)
-        ham_call "${HAM_ARGS[@]}" "${TARGETS[@]}" |
-          filter_get_buildable_targets |
-          filter_get_target_name_and_sort |
-          # exclude targets that look like a file
-          grep -v -e '/' -e '^<.*>' -e '_\(ra\|da\)\.\(dylib\|so\|a\|exe\|lib\|dll\)$'
-        ;;
-      test)
-        ham_call "${HAM_ARGS[@]}" "${TARGETS[@]}" |
-          filter_get_buildable_targets |
-          filter_get_target_name_and_sort |
-          # looks like a test?
-          grep -i -e "^test" -e "_test_" -e "_test$" |
-          # exclude trivial Run/Debug dupes
-          grep -v -i -e "^run_" -e "^debug_"
-        ;;
-      run)
-        ham_call "${HAM_ARGS[@]}" "${TARGETS[@]}" |
-          filter_get_buildable_targets |
-          filter_get_target_name_and_sort |
-          # looks like a runnable?
-          grep -i -e "^run_" -e "_run$"
-        ;;
-      debug)
-        ham_call "${HAM_ARGS[@]}" "${TARGETS[@]}" |
-          filter_get_buildable_targets |
-          filter_get_target_name_and_sort |
-          # looks like a debuggable?
-          grep -i -e "^debug_" -e "_debug$"
-        ;;
-      *)
-        echo "E/Unknown filter '$FILTER'"
-        usage
-        ;;
-    esac
+  case "$FILTER" in
+    raw_all)
+      ham_call "${HAM_ARGS[@]}" "${TARGETS[@]}"
+      ;;
+    raw_tu)
+      ham_call "${HAM_ARGS[@]}" "${TARGETS[@]}" | grep "touched\|update"
+      ;;
+    all)
+      ham_call "${HAM_ARGS[@]}" "${TARGETS[@]}" |
+        filter_get_buildable_targets |
+        filter_get_target_name_and_sort
+      ;;
+    no_file)
+      ham_call "${HAM_ARGS[@]}" "${TARGETS[@]}" |
+        filter_get_buildable_targets |
+        filter_get_target_name_and_sort |
+        # exclude targets that look like a file
+        grep -v -e '/' -e '^<.*>' -e '_\(ra\|da\)\.\(dylib\|so\|a\|exe\|lib\|dll\)$'
+      ;;
+    test)
+      ham_call "${HAM_ARGS[@]}" "${TARGETS[@]}" |
+        filter_get_buildable_targets |
+        filter_get_target_name_and_sort |
+        # looks like a test?
+        grep -i -e "^test" -e "_test_" -e "_test$" |
+        # exclude trivial Run/Debug dupes
+        grep -v -i -e "^run_" -e "^debug_"
+      ;;
+    run)
+      ham_call "${HAM_ARGS[@]}" "${TARGETS[@]}" |
+        filter_get_buildable_targets |
+        filter_get_target_name_and_sort |
+        # looks like a runnable?
+        grep -i -e "^run_" -e "_run$"
+      ;;
+    debug)
+      ham_call "${HAM_ARGS[@]}" "${TARGETS[@]}" |
+        filter_get_buildable_targets |
+        filter_get_target_name_and_sort |
+        # looks like a debuggable?
+        grep -i -e "^debug_" -e "_debug$"
+      ;;
+    *)
+      echo "E/Unknown filter '$FILTER'"
+      usage
+      ;;
+  esac
 
-    errcheck $? ham "Build in $DIR failed."
+  errcheck $? ham "Build in $DIR failed."
 
-    if [[ "$CWD" != "$DIR" ]]; then
-        popd > /dev/null
-    fi
+  if [[ "$CWD" != "$DIR" ]]; then
+    popd >/dev/null
+  fi
 }
 
-
 if [[ "$_ARG_DIRECTORY" != "" ]]; then
-    for dir in "${_ARG_DIRECTORIES[@]}"; do
-        ham_show_targets_in "$dir"
-    done
+  for dir in "${_ARG_DIRECTORIES[@]}"; do
+    ham_show_targets_in "$dir"
+  done
 else
-    # find the _build.ham file
-    export BUILD_HAM_DIR="`ham-search-build-ham.sh`"
-    if [[ -z "$BUILD_HAM_DIR" ]]; then
-        echo "E/Can't find _build.ham !"
-        exit 1
-    fi
-    ham_show_targets_in "$BUILD_HAM_DIR"
+  # find the _build.ham file
+  export BUILD_HAM_DIR="$(ham-search-build-ham.sh)"
+  if [[ -z "$BUILD_HAM_DIR" ]]; then
+    echo "E/Can't find _build.ham !"
+    exit 1
+  fi
+  ham_show_targets_in "$BUILD_HAM_DIR"
 fi
