Added bin/7z-pack-arch & 7z-unpack-arch utilities which pack/unpack archives with a tag file in it which can be used to trigger or skip redownload as needed ;

diff --git a/bin/7z-pack-dir b/bin/7z-pack-dir
--- a/bin/7z-pack-dir
+++ b/bin/7z-pack-dir
@@ -19,4 +19,13 @@ fi
 
 export ARCH="$1"
 export DIR="$2"
-7z a -mmt=on -mx=9 -ms=on -mhc=on -mtc=off -xr\!*/.git/* -xr\!*/.hg/* -xr\!*.DS_Store "$ARCH" "$DIR"
+
+if [ ! -d "${DIR}" ]; then
+    echo "E/Can't find directory '${DIR}'."
+    exit 1
+fi
+
+TMP_ARCH="${ARCH}._tmp_pack_dir_.7z"
+7z a -mmt=on -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on -xr\!*.DS_Store "$TMP_ARCH" "$DIR"
+rm -f "$ARCH"
+mv "$TMP_ARCH" "$ARCH"
