bin: Shell format ;

diff --git a/bin/7z-pack-dir b/bin/7z-pack-dir
--- a/bin/7z-pack-dir
+++ b/bin/7z-pack-dir
@@ -1,28 +1,31 @@
 #!/bin/bash
 export HAM_NO_VER_CHECK=1
-if [[ -z "$HAM_HOME" ]]; then echo "E/HAM_HOME not set !"; exit 1; fi
+if [[ -z "$HAM_HOME" ]]; then
+  echo "E/HAM_HOME not set !"
+  exit 1
+fi
 . "$HAM_HOME/bin/ham-bash-setenv.sh"
 
 print_help() {
-    echo "syntax: 7z-pack-dir ARCHIVE DIRECTORY"
-    exit 1
+  echo "syntax: 7z-pack-dir ARCHIVE DIRECTORY"
+  exit 1
 }
 
 if [[ -z "$1" ]]; then
-    echo "No archive filename specified !"
-    print_help
+  echo "No archive filename specified !"
+  print_help
 fi
 if [[ -z "$2" ]]; then
-    echo "No directory to pack specified !"
-    print_help
+  echo "No directory to pack specified !"
+  print_help
 fi
 
 export ARCH="$1"
 export DIR="$2"
 
 if [ ! -d "${DIR}" ]; then
-    echo "E/Can't find directory '${DIR}'."
-    exit 1
+  echo "E/Can't find directory '${DIR}'."
+  exit 1
 fi
 
 TMP_ARCH="${ARCH}._tmp_pack_dir_.7z"
diff --git a/bin/7z-unpack-arch b/bin/7z-unpack-arch
--- a/bin/7z-unpack-arch
+++ b/bin/7z-unpack-arch
@@ -1,29 +1,32 @@
 #!/bin/bash -e
 export HAM_NO_TAG_CHECK=1
-if [[ -z "$HAM_HOME" ]]; then echo "E/HAM_HOME not set !"; exit 1; fi
+if [[ -z "$HAM_HOME" ]]; then
+  echo "E/HAM_HOME not set !"
+  exit 1
+fi
 . "$HAM_HOME/bin/ham-bash-setenv.sh"
 
 print_help() {
-    echo "syntax: 7z-unpack-arch ARCHIVE DIRECTORY TAG"
-    exit 1
+  echo "syntax: 7z-unpack-arch ARCHIVE DIRECTORY TAG"
+  exit 1
 }
 
 if [[ -z "$1" ]]; then
-    echo "No archive filename specified !"
-    print_help
+  echo "No archive filename specified !"
+  print_help
 fi
 if [[ -z "$2" ]]; then
-    echo "No expected unpacked directory specified !"
-    print_help
+  echo "No expected unpacked directory specified !"
+  print_help
 fi
 if [[ -z "$3" ]]; then
-    echo "No expected archive tag specified !"
-    print_help
+  echo "No expected archive tag specified !"
+  print_help
 fi
 
 ARCH="$1"
 DIR="$2"
-PARENTDIR="`dirname "$DIR"`"
+PARENTDIR="$(dirname "$DIR")"
 TAG_NAME="$3"
 TAG_FILE_NAME=arch_tag_${TAG_NAME}
 
@@ -34,12 +37,12 @@ set -x
 set +x
 
 if [ ${PIPESTATUS[0]} != 0 ]; then
-    echo "E/Extraction failed !"
-    exit 1;
+  echo "E/Extraction failed !"
+  exit 1
 fi
 
 if [ ! -e "${DIR}/${TAG_FILE_NAME}" ]; then
-    echo "E/Can't find '${DIR}/${TAG_FILE_NAME}'."
-    exit 1
+  echo "E/Can't find '${DIR}/${TAG_FILE_NAME}'."
+  exit 1
 fi
 echo "I/Done, unpacked '$ARCH' in '$DIR' with tag '${TAG_FILE_NAME}'."
diff --git a/bin/ham-exec-retry b/bin/ham-exec-retry
--- a/bin/ham-exec-retry
+++ b/bin/ham-exec-retry
@@ -9,13 +9,13 @@ max=5
 # Delay in seconds
 delay=1
 while true; do
-    "$@" && break || {
-        if [[ $n -lt $max ]]; then
-            ((n++))
-            echo "W/Command failed. Attempt $n/$max:"
-            sleep $delay;
-        else
-            ham_exec_fail "E/The command has failed after $n attempts."
-        fi
-    }
+  "$@" && break || {
+    if [[ $n -lt $max ]]; then
+      ((n++))
+      echo "W/Command failed. Attempt $n/$max:"
+      sleep $delay
+    else
+      ham_exec_fail "E/The command has failed after $n attempts."
+    fi
+  }
 done
diff --git a/bin/ham-gdb b/bin/ham-gdb
--- a/bin/ham-gdb
+++ b/bin/ham-gdb
@@ -1,33 +1,36 @@
 #!/bin/bash
 export HAM_NO_VER_CHECK=1
-if [[ -z "$HAM_HOME" ]]; then echo "E/HAM_HOME not set !"; exit 1; fi
+if [[ -z "$HAM_HOME" ]]; then
+  echo "E/HAM_HOME not set !"
+  exit 1
+fi
 . "$HAM_HOME/bin/ham-bash-setenv.sh"
 
 case $HAM_OS in
-    NT*)
-        # RUN_DEBUGGER could have been already set
-        # by the user or by a toolset.
-        if [ ! -f "$RUN_DEBUGGER" ]; then
-            export RUN_DEBUGGER=$(toolset_find_msvc_devenv)
-            if [ ! -f "$RUN_DEBUGGER" ]; then
-                echo "E/Can't find RUN_DEBUGGER (devenv.exe)"
-                return 1
-            fi
-        fi
-        "$RUN_DEBUGGER" -debugexe "$@"
-        ;;
-    OSX*)
-        PATH="/usr/bin:$PATH" lldb -- "$@"
-        ;;
-    LINUX*)
-        if [ "$HAM_GDB_DONT_RUN" == "1" ]; then
-          gdb --args "$@"
-        else
-          gdb -ex run --args "$@"
-        fi
-        ;;
-    *)
-        echo "E/Toolset: Unsupported host OS"
+  NT*)
+    # RUN_DEBUGGER could have been already set
+    # by the user or by a toolset.
+    if [ ! -f "$RUN_DEBUGGER" ]; then
+      export RUN_DEBUGGER=$(toolset_find_msvc_devenv)
+      if [ ! -f "$RUN_DEBUGGER" ]; then
+        echo "E/Can't find RUN_DEBUGGER (devenv.exe)"
         return 1
-        ;;
+      fi
+    fi
+    "$RUN_DEBUGGER" -debugexe "$@"
+    ;;
+  OSX*)
+    PATH="/usr/bin:$PATH" lldb -- "$@"
+    ;;
+  LINUX*)
+    if [ "$HAM_GDB_DONT_RUN" == "1" ]; then
+      gdb --args "$@"
+    else
+      gdb -ex run --args "$@"
+    fi
+    ;;
+  *)
+    echo "E/Toolset: Unsupported host OS"
+    return 1
+    ;;
 esac
diff --git a/bin/ham-pm2 b/bin/ham-pm2
--- a/bin/ham-pm2
+++ b/bin/ham-pm2
@@ -1,43 +1,43 @@
 #!/bin/bash
 . "$HAM_HOME/bin/ham-bash-lib.sh"
-SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
 if [ -z "$PM2_ENV_NAME" ]; then
-    echo "I/ham-pm2: Sourcing _ham_project"
+  echo "I/ham-pm2: Sourcing _ham_project"
 
-    export HAM_NO_VER_CHECK=1
-    WAS_ARGS=( "$@" ) # push arguments
-    set -- ""
-    . hat . > /dev/null
-    set -- "${WAS_ARGS[@]}" # restore arguments
-    if [ -z "$PM2_ENV_NAME" ]; then
-        echo "E/ham-pm2: PM2_ENV_NAME not defined, you should define it in your _ham_project."
-        exit 1
-    fi
+  export HAM_NO_VER_CHECK=1
+  WAS_ARGS=("$@") # push arguments
+  set -- ""
+  . hat . >/dev/null
+  set -- "${WAS_ARGS[@]}" # restore arguments
+  if [ -z "$PM2_ENV_NAME" ]; then
+    echo "E/ham-pm2: PM2_ENV_NAME not defined, you should define it in your _ham_project."
+    exit 1
+  fi
 
-    if [ -z `where_inpath pm2` ]; then
-        echo "E/ham-pm2: pm2 command not found, you should add nodejs as a toolset in your _ham_project. We're in '$(pwd)'."
-        exit 1
-    fi
+  if [ -z $(where_inpath pm2) ]; then
+    echo "E/ham-pm2: pm2 command not found, you should add nodejs as a toolset in your _ham_project. We're in '$(pwd)'."
+    exit 1
+  fi
 
-    export PM2_HOME=$TEMPDIR/pm2-${PM2_ENV_NAME}
-    echo "I/ham-pm2: PM2_ENV_NAME: $PM2_ENV_NAME"
+  export PM2_HOME=$TEMPDIR/pm2-${PM2_ENV_NAME}
+  echo "I/ham-pm2: PM2_ENV_NAME: $PM2_ENV_NAME"
 fi
 
 export PM2_HOME=$TEMPDIR/pm2-${PM2_ENV_NAME}
 echo "I/ham-pm2: PM2_HOME: $PM2_HOME"
 
 usage() {
-    echo "I/ham-pm2: PM2_VERSION: `pm2 -v`"
-    pm2 -h
-    echo ""
-    echo "  ham-pm2 commands:"
-    echo ""
-    echo "    source                               To be sourced at the top of a script to warm up the pm2"
-    echo "                                         environment to run it multiple times."
-    echo "    start-once PM2_APP_NAME START_CMD    Start a pm2 process if it isnt already started."
-    echo ""
-    exit 1
+  echo "I/ham-pm2: PM2_VERSION: $(pm2 -v)"
+  pm2 -h
+  echo ""
+  echo "  ham-pm2 commands:"
+  echo ""
+  echo "    source                               To be sourced at the top of a script to warm up the pm2"
+  echo "                                         environment to run it multiple times."
+  echo "    start-once PM2_APP_NAME START_CMD    Start a pm2 process if it isnt already started."
+  echo ""
+  exit 1
 }
 
 do_pm2_start() {
@@ -46,59 +46,65 @@ do_pm2_start() {
   local START_CMD=$1
   shift
   if [ -z "$1" ]; then
-    (set -x; pm2 start --update-env --name "$PM2_APP_NAME" "$START_CMD")
+    (
+      set -x
+      pm2 start --update-env --name "$PM2_APP_NAME" "$START_CMD"
+    )
   else
-    (set -x; pm2 start --update-env --name "$PM2_APP_NAME" "$START_CMD" -- "$@")
+    (
+      set -x
+      pm2 start --update-env --name "$PM2_APP_NAME" "$START_CMD" -- "$@"
+    )
   fi
 }
 
 if [ -z "$1" ]; then
-    usage
+  usage
 elif [ "$1" == source ]; then
-    echo -n ""
+  echo -n ""
 elif [ "$1" == start-once ]; then
-    shift
-    PM2_APP_NAME="$1"
-    if [ -z "$PM2_APP_NAME" ]; then
-        echo "E/ham-pm2: start-once: PM2_APP_NAME not specified."
-        exit 1
-    fi
-    shift
-    START_CMD="$1"
-    if [ -z "$START_CMD" ]; then
-        echo "E/ham-pm2: start-once: START_CMD not specified."
-        exit 1
-    fi
-    shift
+  shift
+  PM2_APP_NAME="$1"
+  if [ -z "$PM2_APP_NAME" ]; then
+    echo "E/ham-pm2: start-once: PM2_APP_NAME not specified."
+    exit 1
+  fi
+  shift
+  START_CMD="$1"
+  if [ -z "$START_CMD" ]; then
+    echo "E/ham-pm2: start-once: START_CMD not specified."
+    exit 1
+  fi
+  shift
 
-    if [[ `pm2 info "$PM2_APP_NAME" | grep 'status.*online'` ]]; then
-        echo "I/ham-pm2: '$PM2_APP_NAME' already started and online."
-    else
-        echo "I/ham-pm2: '$PM2_APP_NAME' not online, starting cmd: $START_CMD $@"
-        do_pm2_start "$PM2_APP_NAME" "$START_CMD" "$@"
-    fi
-elif [ "$1" == restart ]; then
-    shift
-    PM2_APP_NAME="$1"
-    if [ -z "$PM2_APP_NAME" ]; then
-        echo "E/ham-pm2: restart: PM2_APP_NAME not specified."
-        exit 1
-    fi
-    shift
-    START_CMD="$1"
-    if [ -z "$START_CMD" ]; then
-        echo "E/ham-pm2: restart: START_CMD not specified."
-        exit 1
-    fi
-    shift
-
-    if [[ `pm2 info "$PM2_APP_NAME" | grep 'status.*online'` ]]; then
-        echo "I/ham-pm2: '$PM2_APP_NAME' already started and online, stopping it first."
-        pm2 stop "$PM2_APP_NAME"
-    fi
-    echo "I/ham-pm2: '$Pm2_APP_NAME' starting cmd: $START_CMD $@"
+  if [[ $(pm2 info "$PM2_APP_NAME" | grep 'status.*online') ]]; then
+    echo "I/ham-pm2: '$PM2_APP_NAME' already started and online."
+  else
+    echo "I/ham-pm2: '$PM2_APP_NAME' not online, starting cmd: $START_CMD $@"
     do_pm2_start "$PM2_APP_NAME" "$START_CMD" "$@"
+  fi
+elif [ "$1" == restart ]; then
+  shift
+  PM2_APP_NAME="$1"
+  if [ -z "$PM2_APP_NAME" ]; then
+    echo "E/ham-pm2: restart: PM2_APP_NAME not specified."
+    exit 1
+  fi
+  shift
+  START_CMD="$1"
+  if [ -z "$START_CMD" ]; then
+    echo "E/ham-pm2: restart: START_CMD not specified."
+    exit 1
+  fi
+  shift
+
+  if [[ $(pm2 info "$PM2_APP_NAME" | grep 'status.*online') ]]; then
+    echo "I/ham-pm2: '$PM2_APP_NAME' already started and online, stopping it first."
+    pm2 stop "$PM2_APP_NAME"
+  fi
+  echo "I/ham-pm2: '$Pm2_APP_NAME' starting cmd: $START_CMD $@"
+  do_pm2_start "$PM2_APP_NAME" "$START_CMD" "$@"
 else
-    set -e
-    pm2 "$@"
+  set -e
+  pm2 "$@"
 fi
diff --git a/bin/ham-toolset-build b/bin/ham-toolset-build
--- a/bin/ham-toolset-build
+++ b/bin/ham-toolset-build
@@ -5,39 +5,39 @@ TS_DL_DIR="${HAM_HOME}/toolsets/_dl"
 mkdir -p "${TS_DL_DIR}"
 
 usage() {
-    echo "usage:"
-    echo "  ham-toolset-build (dontpack) NAME LOA VER"
-    echo ""
-    echo "notes:"
-    echo "  'dontpack' will only update the version tag file and"
-    echo "  skip creating the actual archive"
-    echo ""
-    echo "example:"
-    echo "  # Package multiplatform toolset binaries"
-    echo "  ham-toolset-build rclone dist $(ver_date)"
-    echo "  # Package host platform toolset binaries"
-    echo "  ham-toolset-build ffmpeg $HAM_BIN_LOA $(ver_date)"
-    echo "  # Dontpack and test setup-toolset.sh"
-    echo "  ham-toolset-build dontpack zig $HAM_BIN_LOA v0_11_0 && HAM_TOOLSET_DL_URL=none hat zig_default"
-    exit 1
+  echo "usage:"
+  echo "  ham-toolset-build (dontpack) NAME LOA VER"
+  echo ""
+  echo "notes:"
+  echo "  'dontpack' will only update the version tag file and"
+  echo "  skip creating the actual archive"
+  echo ""
+  echo "example:"
+  echo "  # Package multiplatform toolset binaries"
+  echo "  ham-toolset-build rclone dist $(ver_date)"
+  echo "  # Package host platform toolset binaries"
+  echo "  ham-toolset-build ffmpeg $HAM_BIN_LOA $(ver_date)"
+  echo "  # Dontpack and test setup-toolset.sh"
+  echo "  ham-toolset-build dontpack zig $HAM_BIN_LOA v0_11_0 && HAM_TOOLSET_DL_URL=none hat zig_default"
+  exit 1
 }
 
 if [[ "$1" == "dontpack" ]]; then
-    DONT_PACK=yes
-    shift
+  DONT_PACK=yes
+  shift
 fi
 
 if [ -z "$1" ]; then
-    echo "E/Toolset NAME not specified."
-    usage
+  echo "E/Toolset NAME not specified."
+  usage
 fi
 if [ -z "$2" ]; then
-    echo "E/Toolset LOA not specified."
-    usage
+  echo "E/Toolset LOA not specified."
+  usage
 fi
 if [ -z "$3" ]; then
-    echo "E/Toolset VER not specified."
-    usage
+  echo "E/Toolset VER not specified."
+  usage
 fi
 
 TS_NAME=$1
@@ -48,14 +48,14 @@ TS_VER_NAME=${TS_NAME}_${TS_LOA}_${TS_VER}
 TS_VER_FILE_NAME=toolset_${TS_VER_NAME}
 
 if [ ! -d "$TS_DIR" ]; then
-    echo "Can't find toolset folder: ${TS_DIR}"
-    usage
+  echo "Can't find toolset folder: ${TS_DIR}"
+  usage
 fi
 
 set -ex
 cd "$TS_DIR"
 rm -f toolset_${TS_NAME}_*
-echo "${TS_VER_FILE_NAME}" > "${TS_VER_FILE_NAME}"
+echo "${TS_VER_FILE_NAME}" >"${TS_VER_FILE_NAME}"
 
 toolset_unquarantine_dir "$TS_DIR/"
 
diff --git a/bin/niw b/bin/niw
--- a/bin/niw
+++ b/bin/niw
@@ -1,10 +1,10 @@
 #!/bin/bash
 if [[ -z "$NILANG_DIR" ]]; then
-    NILANG_DIR="$WORK/niLang"
+  NILANG_DIR="$WORK/niLang"
 fi
 SCRIPT_DIR="$NILANG_DIR/bin"
 if [[ ! -e "$SCRIPT_DIR/ni" ]]; then
-    echo "E/Couldn't find ni at '$SCRIPT_DIR/ni'."
-    exit 1
+  echo "E/Couldn't find ni at '$SCRIPT_DIR/ni'."
+  exit 1
 fi
 "$NILANG_DIR/bin/niw" -I "$HAM_HOME/scripts" "$@"
