Added xslt_tools toolset to build Ni ; Replaced the java_jre6 toolset with the java_jdk16 toolset ; ham-toolset script can take multiple toolset as parameter ;

diff --git a/bin/ham-toolset b/bin/ham-toolset
--- a/bin/ham-toolset
+++ b/bin/ham-toolset
@@ -15,12 +15,16 @@ toolset_info() {
     echo "$HAM_TOOLSET_VERSIONS"
     echo "======================================================="
 }
-. ham-toolset-import.sh $1
-if [ $? != 0 ]; then
-    echo "E/Toolset '$1' setup failed !"
-    return 1
-else
-    echo "I/Toolset '$1' setup successfull."
-    toolset_info
-    update_prompt
-fi
+
+for ARG in "$@"
+do
+    . ham-toolset-import.sh $ARG
+    if [ $? != 0 ]; then
+        echo "E/Toolset '$ARG' setup failed !"
+        return 1
+    else
+        echo "I/Toolset '$ARG' setup successfull."
+    fi
+done
+toolset_info
+update_prompt
diff --git a/toolsets/xslt_tools/xslt_tools-xslt2 b/toolsets/xslt_tools/xslt_tools-xslt2
--- a/toolsets/xslt_tools/xslt_tools-xslt2
+++ b/toolsets/xslt_tools/xslt_tools-xslt2
@@ -3,7 +3,8 @@
 if [ -e "${1}" ]; then
     XSLTPATH=$1
 else
-    XSLTPATH=`nativedir $AGLDEVENVSRC`/scripts_gen/$1.xslt
+    echo "Can't find XSLT: $1"
+    exit 1
 fi
 if [ -z "$3" ]; then
     OUTPUT=
