bin/ham-install-os-packages: Linux install for pacman distro (SteamOS) ;

diff --git a/bin/ham-install-os-packages b/bin/ham-install-os-packages
--- a/bin/ham-install-os-packages
+++ b/bin/ham-install-os-packages
@@ -48,6 +48,17 @@ case $HAM_OS in
         # install all our required packages
         ham-apt-get-install software-properties-common build-essential clang git lld curl ffmpeg file freeglut3-dev git g++ gcc git htop jq libcurl4-openssl-dev libdw-dev libunwind-dev libsdl2-dev libssl-dev libudev-dev mc mesa-common-dev mesa-utils net-tools netcat ntpdate p7zip-full procps pkg-config python3 python3-pip wget xsltproc autossh tcpdump
       )
+    elif [ "$(type pacman 2>/dev/null | wc -l)" = 1 ]; then
+      echo "### Installing packages required by ham on Linux (pacman) ###"
+      echo "I/Installing pacman packages"
+      (
+        set -ex
+        sudo pacman -Syu
+        sudo pacman --noconfirm -S base-devel gcc clang lld curl ffmpeg file git\
+             glibc mesa libglvnd freeglut linux-api-headers sdl2 xorgproto libx11\
+             htop jq openssl mc net-tools gnu-netcat ntp p7zip procps\
+             pkg-config python python-pip wget libxslt autossh tcpdump
+      )
     else
       echo "E/Unsupported LINUX package manager"
       exit 1
