specs/toolsets/xslt_tools: Fix a different error code being returned with Java 11 leading to toolset import failure when checking the xslt saxon version ;

diff --git a/toolsets/xslt_tools/xslt_tools-saxon b/toolsets/xslt_tools/xslt_tools-saxon
--- a/toolsets/xslt_tools/xslt_tools-saxon
+++ b/toolsets/xslt_tools/xslt_tools-saxon
@@ -1,7 +1,16 @@
 #!/bin/bash
 . ham-bash-lib.sh
 export SAXONPATH="${HAM_HOME}/toolsets/xslt_tools/jars/saxon9he.jar"
-if [ -z "$1" ]; then
+if [ "$1" == "-version" ]; then
+    VERSION=`java -cp "$SAXONPATH" net.sf.saxon.Transform 2>&1 | grep Saxon`
+    if [ -z "$VERSION" ]; then
+      echo "E/Can't get Saxon version."
+      exit 1
+    else
+      echo $VERSION
+      exit 0
+    fi
+elif [ -z "$1" ]; then
     # echo "1:" java -cp "$SAXONPATH" net.sf.saxon.Transform
     java -cp "$SAXONPATH" net.sf.saxon.Transform
 elif [ -z "$3" ]; then
