toolsets/nicgc: Add Linux support ;

diff --git a/toolsets/nicgc/nicgc b/toolsets/nicgc/nicgc
--- a/toolsets/nicgc/nicgc
+++ b/toolsets/nicgc/nicgc
@@ -7,7 +7,7 @@ cd "$CWD"
 case $HAM_OS in
     OSX*)
         # set -ex
-        echo "I/nicgc running in Wine"
+        echo "I/nicgc running in Wine on macOS"
         if [ "$1" == "-v" ]; then
             if [ ! -e "$SCRIPT_DIR/osx-x64/bin-nt-x64/nicgc_ra.exe" ]; then
                 echo "E/Can't find nicgc_ra.exe at: $SCRIPT_DIR/osx-x64/bin-nt-x64/nicgc_ra.exe"
@@ -37,6 +37,21 @@ case $HAM_OS in
             export NI_CGC_EXE="cantfind_ni_$BUILD"
         fi
         "${NI_CGC_EXE}" "$@"
+        ;;
+    LINUX*)
+        echo "I/nicgc running in Wine on Linux"
+        if [ "$1" == "-v" ]; then
+            if [ ! -e "$SCRIPT_DIR/lin-x64/bin-nt-x64/nicgc_ra.exe" ]; then
+                echo "E/Can't find nicgc_ra.exe at: $SCRIPT_DIR/lin-x64/bin-nt-x64/nicgc_ra.exe"
+                exit 1
+            fi
+            # This is a hack, wine is attrociously slow when we pipe the
+            # output which we do when initializing the toolsets. By slow I
+            # mean: -v takes 3-4s vs < 0.5s when not pipeing.
+            echo "Ni Shader Compiler Version 5.0"
+        else
+            WINEDEBUG=-all wine64 "$SCRIPT_DIR/lin-x64/bin-nt-x64/nicgc_ra.exe" "$@"
+        fi
         ;;
     *)
         echo "E/Toolset: Unsupported host OS"
