toolsets/repos: Enhance git scripts with better error handling and logging; Added repos-push; Updated git-log with graph mode and improved output.

diff --git a/toolsets/repos/git-push b/toolsets/repos/git-push
--- a/toolsets/repos/git-push
+++ b/toolsets/repos/git-push
@@ -1,4 +1,6 @@
 #!/bin/bash -e
+. ham-bash-lib.sh
+
 usage() {
   echo "usage: git-push (origin) BRANCH"
   echo ""
@@ -16,6 +18,9 @@ if [ -z "$1" ]; then
   usage
 fi
 
+REPO_NAME=$(basename "$(git rev-parse --show-toplevel)")
+trap 'log_error "Repo '"'"'$REPO_NAME'"'"' git-push failed."' ERR
+
 if [ $# = 1 ]; then
   ORIGIN=origin
   BRANCH=$1
@@ -26,10 +31,11 @@ fi
 
 BRANCH=$(git-get-branch-name "$BRANCH")
 
-echo "I/Status"
+log_info "Status"
 git-status short
-echo "I/Pushing branch '$BRANCH'."
+log_info "Pushing branch '$BRANCH'."
 (
   set -x
   git push --force-with-lease "$ORIGIN" "$BRANCH"
 )
+log_success "Repo '$REPO_NAME' git-push succeeded."
diff --git a/toolsets/repos/git-rebase b/toolsets/repos/git-rebase
--- a/toolsets/repos/git-rebase
+++ b/toolsets/repos/git-rebase
@@ -11,6 +11,9 @@ if [ -z "$1" ]; then
   help
 fi
 
+REPO_NAME=$(basename "$(git rev-parse --show-toplevel)")
+trap 'log_error "Repo '"'"'$REPO_NAME'"'"' git-rebase failed."' ERR
+
 BRANCH=$(git-get-branch-name "$1")
 shift
 
@@ -29,4 +32,4 @@ fi
 
 log_info "git-rebase: Rebasing on '$BRANCH'."
 git rebase "${GIT_PARAMS[@]}" "$BRANCH" "$@"
-log_info "git-rebase: Done."
+log_success "Repo '$REPO_NAME' git-rebase on '$BRANCH' succeeded."
