Updates for macOS & iOS Jenkins build ;

diff --git a/toolsets/repos/repos-git-batch b/toolsets/repos/repos-git-batch
--- a/toolsets/repos/repos-git-batch
+++ b/toolsets/repos/repos-git-batch
@@ -35,6 +35,10 @@ fi
 if [[ "$1" == "." ]]; then
     REPOS_CWD=`repos-list-cwd`
 else
+    if [ ! -e "$1" ]; then
+        echo "E/Can't find repos list '$1'."
+        exit 1
+    fi
     REPOS_CWD=`cat "$1"`
     REPOS_CWD=$(eval echo \"$REPOS_CWD\")
 fi
