toolsets/*: Commit automatic style fixes from shell linter ;

diff --git a/toolsets/adr_base/adr-install-apk b/toolsets/adr_base/adr-install-apk
--- a/toolsets/adr_base/adr-install-apk
+++ b/toolsets/adr_base/adr-install-apk
@@ -3,36 +3,36 @@
 PACKAGE_CLASS=${2}
 APK_PATH=${1}
 if [ -z "${APK_PATH}" -o -z "${PACKAGE_CLASS}" ]; then
-    echo "E/Syntax: adr-install-apk APK_PATH PACKAGE_CLASS"
-    exit 1
+  echo "E/Syntax: adr-install-apk APK_PATH PACKAGE_CLASS"
+  exit 1
 fi
 if [ ! -e "${APK_PATH}" ]; then
-    echo "E/Can't find apk: '${APK_PATH}' !"
-    exit 1
+  echo "E/Can't find apk: '${APK_PATH}' !"
+  exit 1
 fi
-APK_NAME=`basename "${APK_PATH}"`
+APK_NAME=$(basename "${APK_PATH}")
 echo "# APK_NAME: ${APK_NAME}"
-APK_PREV_MD5=`adb shell "cat //sdcard/${APK_NAME}.md5"`
+APK_PREV_MD5=$(adb shell "cat //sdcard/${APK_NAME}.md5")
 echo "# APK_PREV_MD5: ${APK_PREV_MD5}"
-APK_MD5=`md5sum -b "${APK_PATH}" | cut -b-32`
+APK_MD5=$(md5sum -b "${APK_PATH}" | cut -b-32)
 echo "# APK_MD5: ${APK_MD5}"
-PACKAGE_INSTALLED=`adb shell pm list packages | grep "${PACKAGE_CLASS}"`
+PACKAGE_INSTALLED=$(adb shell pm list packages | grep "${PACKAGE_CLASS}")
 echo "# PACKAGE_INSTALLED: ${PACKAGE_INSTALLED}"
 
 if [ "${PACKAGE_INSTALLED}" != "package:${PACKAGE_CLASS}" ]; then
-    echo "'${PACKAGE_CLASS}' is not installed."
-    # Clear the md5 to force installation
-    APK_MD5=""
+  echo "'${PACKAGE_CLASS}' is not installed."
+  # Clear the md5 to force installation
+  APK_MD5=""
 else
-    echo "'${PACKAGE_CLASS}' is already installed."
+  echo "'${PACKAGE_CLASS}' is already installed."
 fi
 
 if [ ! -z "${APK_PREV_MD5}" -a "${APK_MD5}" == "${APK_PREV_MD5}" ]; then
-    echo "'${APK_NAME}' is up-to-date."
+  echo "'${APK_NAME}' is up-to-date."
 else
-    echo "'${APK_NAME}' is not up-to-date."
-    adb install -r "${1}"
-    errcheck $? "Can't install ${APK_NAME} on the device !"
-    adb shell "echo ${APK_MD5} > //sdcard/${APK_NAME}.md5"
-    errcheck $? "Can't put ${APK_NAME}.md5 on the device !"
+  echo "'${APK_NAME}' is not up-to-date."
+  adb install -r "${1}"
+  errcheck $? "Can't install ${APK_NAME} on the device !"
+  adb shell "echo ${APK_MD5} > //sdcard/${APK_NAME}.md5"
+  errcheck $? "Can't put ${APK_NAME}.md5 on the device !"
 fi
diff --git a/toolsets/rclone/ham-sync-resources b/toolsets/rclone/ham-sync-resources
--- a/toolsets/rclone/ham-sync-resources
+++ b/toolsets/rclone/ham-sync-resources
@@ -1,92 +1,95 @@
 #!/bin/bash
 export HAM_NO_VER_CHECK=1
-if [[ -z "$HAM_HOME" ]]; then echo "E/HAM_HOME not set !"; exit 1; fi
+if [[ -z "$HAM_HOME" ]]; then
+  echo "E/HAM_HOME not set !"
+  exit 1
+fi
 . "$HAM_HOME/bin/ham-bash-setenv.sh"
 
 # the help
 usage() {
-    echo ""
-    echo "usage: ham-sync-resources project dir command (doit)"
-    echo ""
-    echo "  ham-rclone is used to sync the resources, it expects a rclone.conf"
-    echo "  with a config for the specified project name."
-    echo ""
-    echo "command:"
-    echo "  pull   Pull data from the server to the local data folder."
-    echo "  push   Push data from the local data folder to the server."
-    echo ""
-    echo "  pull_delete  Pull data from the server to the local data folder,"
-    echo "               deletes from the local copy any file not present."
-    echo "               on the server"
-    echo "  push_delete  Push data from the local data folder to the server,"
-    echo "               deletes from the server any file not present locally."
-    echo ""
-    echo "  ls     List the files currently on the server."
-    echo ""
-    echo "example:"
-    echo "  # Get the new data from the server (dry run)"
-    echo "  ham-sync-resources Playground_202010 . pull"
-    echo "  # Get the new data from the server"
-    echo "  ham-sync-resources Playground_202010 . pull doit"
-    echo "  # Push the new data from the server (dry run)"
-    echo "  ham-sync-resources Playground_202010 . push"
-    echo "  # Push the new data from the server"
-    echo "  ham-sync-resources Playground_202010 . push doit"
-    echo ""
+  echo ""
+  echo "usage: ham-sync-resources project dir command (doit)"
+  echo ""
+  echo "  ham-rclone is used to sync the resources, it expects a rclone.conf"
+  echo "  with a config for the specified project name."
+  echo ""
+  echo "command:"
+  echo "  pull   Pull data from the server to the local data folder."
+  echo "  push   Push data from the local data folder to the server."
+  echo ""
+  echo "  pull_delete  Pull data from the server to the local data folder,"
+  echo "               deletes from the local copy any file not present."
+  echo "               on the server"
+  echo "  push_delete  Push data from the local data folder to the server,"
+  echo "               deletes from the server any file not present locally."
+  echo ""
+  echo "  ls     List the files currently on the server."
+  echo ""
+  echo "example:"
+  echo "  # Get the new data from the server (dry run)"
+  echo "  ham-sync-resources Playground_202010 . pull"
+  echo "  # Get the new data from the server"
+  echo "  ham-sync-resources Playground_202010 . pull doit"
+  echo "  # Push the new data from the server (dry run)"
+  echo "  ham-sync-resources Playground_202010 . push"
+  echo "  # Push the new data from the server"
+  echo "  ham-sync-resources Playground_202010 . push doit"
+  echo ""
 
-    if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
-        # sourced...
-        return 1
-    else
-        # regular call
-        exit 1
-    fi
+  if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
+    # sourced...
+    return 1
+  else
+    # regular call
+    exit 1
+  fi
 }
 
 SYNC_PROJECT=$1
 shift
 if [[ -z "$SYNC_PROJECT" ]]; then
-    echo "E/Project not specified."
-    usage
-    exit 1
+  echo "E/Project not specified."
+  usage
+  exit 1
 fi
 
 SYNC_DIR=$1
 shift
 if [[ -z "$SYNC_DIR" ]]; then
-    echo "E/Dir not specified."
-    usage
-    exit 1
+  echo "E/Dir not specified."
+  usage
+  exit 1
 fi
 
 SYNC_COMMAND=$1
 shift
 if [[ -z "$SYNC_COMMAND" ]]; then
-    echo "E/Command not specified."
-    usage
-    exit 1
+  echo "E/Command not specified."
+  usage
+  exit 1
 fi
 
 if [[ "$1" == "doit" ]]; then
-    echo "I/Do it."
-    DOIT="yes"
-    shift
+  echo "I/Do it."
+  DOIT="yes"
+  shift
 else
-    DOIT=""
+  DOIT=""
 fi
 
 # Local & destination folders
-BASE_LOCAL_DIR="`pwd`/src"
+BASE_LOCAL_DIR="$(pwd)/src"
 if [[ -e "$BASE_LOCAL_DIR/_sync_data" ]]; then
-  BASE_LOCAL_DIR="`pwd`/src"
+  BASE_LOCAL_DIR="$(pwd)/src"
 else
-  BASE_LOCAL_DIR="`pwd`/data"
+  BASE_LOCAL_DIR="$(pwd)/data"
 fi
 
 if [ "$SYNC_DIR" == "." ]; then
-    LOCAL_DIR="${BASE_LOCAL_DIR}"
+  LOCAL_DIR="${BASE_LOCAL_DIR}"
 else
-    LOCAL_DIR="${BASE_LOCAL_DIR}/${SYNC_DIR}"
+  LOCAL_DIR="${BASE_LOCAL_DIR}/${SYNC_DIR}"
 fi
 BASE_REMOTE_DIR="/ham_sync/$SYNC_PROJECT"
 REMOTE_DIR="${BASE_REMOTE_DIR}/${SYNC_DIR}"
@@ -94,22 +97,22 @@ REMOTE_DIR="${BASE_REMOTE_DIR}/${SYNC_DIR}"
 # Validate using _sync_data
 SYNC_DATA_PATH="$BASE_LOCAL_DIR/_sync_data"
 if [[ ! -e "$SYNC_DATA_PATH" ]]; then
-    echo "E/Couldn't find '$SYNC_DATA_PATH' which is required to make sure that you're syncing the right folder."
-    exit 1
+  echo "E/Couldn't find '$SYNC_DATA_PATH' which is required to make sure that you're syncing the right folder."
+  exit 1
 fi
-SYNC_DATA_SYNC_PROJECT=`head -1 "$SYNC_DATA_PATH"`
+SYNC_DATA_SYNC_PROJECT=$(head -1 "$SYNC_DATA_PATH")
 if [[ "$SYNC_DATA_SYNC_PROJECT" != "# $SYNC_PROJECT" ]]; then
-    echo "E/_sync_data project name doesnt match, expecting '# $SYNC_PROJECT', but _sync_data says '$SYNC_DATA_SYNC_PROJECT'."
-    echo "I/The _sync_data file should use the rclone filter file format with the commented project name as the first line."
-    echo "I/See: https://rclone.org/filtering/#filter-from-read-filtering-patterns-from-a-file"
-    exit 1
+  echo "E/_sync_data project name doesnt match, expecting '# $SYNC_PROJECT', but _sync_data says '$SYNC_DATA_SYNC_PROJECT'."
+  echo "I/The _sync_data file should use the rclone filter file format with the commented project name as the first line."
+  echo "I/See: https://rclone.org/filtering/#filter-from-read-filtering-patterns-from-a-file"
+  exit 1
 fi
 
 echo "I/Sync Project: $SYNC_PROJECT"
 
 PARAMS=()
 if [[ "$SYNC_COMMAND" != "arch_"* ]]; then
-    PARAMS=("${PARAMS[@]}" --filter-from "$SYNC_DATA_PATH")
+  PARAMS=("${PARAMS[@]}" --filter-from "$SYNC_DATA_PATH")
 fi
 # PARAMS=("${PARAMS[@]}" --fast-list)
 # PARAMS=("${PARAMS[@]}" --max-age 1h)
@@ -119,98 +122,126 @@ PARAMS=("${PARAMS[@]}" --transfers=${HAM_SYNC_NUM_TRANSFERS:-16})
 PARAMS=("${PARAMS[@]}" --stats 60s)
 PARAMS=("${PARAMS[@]}" -v)
 if [ "$DOIT" != "yes" ]; then
-    PARAMS=("${PARAMS[@]}" --dry-run)
+  PARAMS=("${PARAMS[@]}" --dry-run)
 else
-    PARAMS=("${PARAMS[@]}" --progress)
+  PARAMS=("${PARAMS[@]}" --progress)
 fi
 
 arch_init() {
-    export ARCH_NAME=$1
-    if [ -z "$ARCH_NAME" ]; then
-        echo "E/Archive name not specified."
-        usage
-    fi
-    shift
-    export ARCH_VERTAG=$1
-    if [ -z "$ARCH_VERTAG" ]; then
-        echo "E/Archive version tag not specified."
-        usage
-    fi
-    shift
-    export ARCH_FN="$LOCAL_DIR/_arch_${ARCH_NAME}_${ARCH_VERTAG}.7z"
-    export ARCH_DIR="$LOCAL_DIR/arch-${ARCH_NAME}"
+  export ARCH_NAME=$1
+  if [ -z "$ARCH_NAME" ]; then
+    echo "E/Archive name not specified."
+    usage
+  fi
+  shift
+  export ARCH_VERTAG=$1
+  if [ -z "$ARCH_VERTAG" ]; then
+    echo "E/Archive version tag not specified."
+    usage
+  fi
+  shift
+  export ARCH_FN="$LOCAL_DIR/_arch_${ARCH_NAME}_${ARCH_VERTAG}.7z"
+  export ARCH_DIR="$LOCAL_DIR/arch-${ARCH_NAME}"
 
-    echo "I/ARCH_FN: $ARCH_FN"
-    echo "I/ARCH_DIR: $ARCH_DIR"
-    echo "I/ARCH_VERTAG: $ARCH_VERTAG"
+  echo "I/ARCH_FN: $ARCH_FN"
+  echo "I/ARCH_DIR: $ARCH_DIR"
+  echo "I/ARCH_VERTAG: $ARCH_VERTAG"
 }
 
 case "$SYNC_COMMAND" in
-    push)
-        echo "I/Pushing from data to server..."
-        (set -x; ham-rclone copy "${PARAMS[@]}" "$LOCAL_DIR" "$SYNC_PROJECT:$REMOTE_DIR")
-        ;;
-    push_delete)
-        echo "I/Pushing from data to server, and deleting files removed locally from the server..."
-        (set -x; ham-rclone sync "${PARAMS[@]}" "$LOCAL_DIR" "$SYNC_PROJECT:$REMOTE_DIR")
-        ;;
-    pull)
-        echo "I/Pulling from server to local data folder..."
-        (set -x; ham-rclone copy "${PARAMS[@]}" "$SYNC_PROJECT:$REMOTE_DIR" "$LOCAL_DIR")
-        ;;
-    pull_delete)
-        echo "I/Pulling from server to local data folder, and deleting local files that have been removed from the server..."
-        (set -x; ham-rclone sync "${PARAMS[@]}" "$SYNC_PROJECT:$REMOTE_DIR" "$LOCAL_DIR")
-        ;;
-    ls)
-        echo "I/Listing files on the remote..."
-        (set -x;
-         ham-rclone ls "$SYNC_PROJECT:$REMOTE_DIR")
-        ;;
-    arch_make)
-        echo "I/Making archive..."
-        arch_init $1 $2
-        (set -x ; 7z-pack-arch "$ARCH_FN" "$ARCH_DIR" "$ARCH_VERTAG")
-        ;;
-    arch_push)
-        echo "I/Push an archive..."
-        arch_init $1 $2
-        if [ -e "$ARCH_FN" ]; then
-            echo "I/Archive already exist."
-        else
-            echo "I/Making archive..."
-            (set -x ; 7z-pack-arch "$ARCH_FN" "$ARCH_DIR" "$ARCH_VERTAG")
-        fi
-        echo "I/Pushing to server..."
-        BASENAME=`basename "$ARCH_FN"`
-        (set -x; ham-rclone copy "${PARAMS[@]}" "$LOCAL_DIR/$BASENAME" "$SYNC_PROJECT:$REMOTE_DIR")
-        ;;
-    arch_pull)
-        echo "I/Pull an archive..."
-        arch_init $1 $2
-        ARCH_TAG_FN="$ARCH_DIR/arch_tag_${ARCH_VERTAG}"
-        echo "I/ARCH_TAG_FN: $ARCH_TAG_FN"
-        if [ -e "$ARCH_TAG_FN" ]; then
-            echo "I/Archive already downloaded and unpacked, nothing to do."
-        else
-            if [ -e "$ARCH_FN" ]; then
-                echo "I/Archive already downloaded."
-            else
-                echo "I/Getting archive..."
-                BASENAME=`basename "$ARCH_FN"`
-                (set -x; ham-rclone copy "${PARAMS[@]}"  "$SYNC_PROJECT:$REMOTE_DIR/$BASENAME" "$LOCAL_DIR")
-            fi
-            echo "I/Unpacking archive..."
-            (set -x ;
-             rm -Rf "$ARCH_DIR" ;
-             7z-unpack-arch "$ARCH_FN" "$ARCH_DIR" "$ARCH_VERTAG" ;
-             rm "$ARCH_FN")
-        fi
-        ;;
-    *)
-        echo "E/Unknown command '$SYNC_COMMAND'"
-        usage
-        ;;
+  push)
+    echo "I/Pushing from data to server..."
+    (
+      set -x
+      ham-rclone copy "${PARAMS[@]}" "$LOCAL_DIR" "$SYNC_PROJECT:$REMOTE_DIR"
+    )
+    ;;
+  push_delete)
+    echo "I/Pushing from data to server, and deleting files removed locally from the server..."
+    (
+      set -x
+      ham-rclone sync "${PARAMS[@]}" "$LOCAL_DIR" "$SYNC_PROJECT:$REMOTE_DIR"
+    )
+    ;;
+  pull)
+    echo "I/Pulling from server to local data folder..."
+    (
+      set -x
+      ham-rclone copy "${PARAMS[@]}" "$SYNC_PROJECT:$REMOTE_DIR" "$LOCAL_DIR"
+    )
+    ;;
+  pull_delete)
+    echo "I/Pulling from server to local data folder, and deleting local files that have been removed from the server..."
+    (
+      set -x
+      ham-rclone sync "${PARAMS[@]}" "$SYNC_PROJECT:$REMOTE_DIR" "$LOCAL_DIR"
+    )
+    ;;
+  ls)
+    echo "I/Listing files on the remote..."
+    (
+      set -x
+      ham-rclone ls "$SYNC_PROJECT:$REMOTE_DIR"
+    )
+    ;;
+  arch_make)
+    echo "I/Making archive..."
+    arch_init $1 $2
+    (
+      set -x
+      7z-pack-arch "$ARCH_FN" "$ARCH_DIR" "$ARCH_VERTAG"
+    )
+    ;;
+  arch_push)
+    echo "I/Push an archive..."
+    arch_init $1 $2
+    if [ -e "$ARCH_FN" ]; then
+      echo "I/Archive already exist."
+    else
+      echo "I/Making archive..."
+      (
+        set -x
+        7z-pack-arch "$ARCH_FN" "$ARCH_DIR" "$ARCH_VERTAG"
+      )
+    fi
+    echo "I/Pushing to server..."
+    BASENAME=$(basename "$ARCH_FN")
+    (
+      set -x
+      ham-rclone copy "${PARAMS[@]}" "$LOCAL_DIR/$BASENAME" "$SYNC_PROJECT:$REMOTE_DIR"
+    )
+    ;;
+  arch_pull)
+    echo "I/Pull an archive..."
+    arch_init $1 $2
+    ARCH_TAG_FN="$ARCH_DIR/arch_tag_${ARCH_VERTAG}"
+    echo "I/ARCH_TAG_FN: $ARCH_TAG_FN"
+    if [ -e "$ARCH_TAG_FN" ]; then
+      echo "I/Archive already downloaded and unpacked, nothing to do."
+    else
+      if [ -e "$ARCH_FN" ]; then
+        echo "I/Archive already downloaded."
+      else
+        echo "I/Getting archive..."
+        BASENAME=$(basename "$ARCH_FN")
+        (
+          set -x
+          ham-rclone copy "${PARAMS[@]}" "$SYNC_PROJECT:$REMOTE_DIR/$BASENAME" "$LOCAL_DIR"
+        )
+      fi
+      echo "I/Unpacking archive..."
+      (
+        set -x
+        rm -Rf "$ARCH_DIR"
+        7z-unpack-arch "$ARCH_FN" "$ARCH_DIR" "$ARCH_VERTAG"
+        rm "$ARCH_FN"
+      )
+    fi
+    ;;
+  *)
+    echo "E/Unknown command '$SYNC_COMMAND'"
+    usage
+    ;;
 esac
 
 echo "I/Done"
diff --git a/toolsets/repos/git-stash b/toolsets/repos/git-stash
--- a/toolsets/repos/git-stash
+++ b/toolsets/repos/git-stash
@@ -1,107 +1,107 @@
 #!/bin/bash
 help() {
-    echo "usage:"
-    echo "  git-stash push|find STASH_NAME"
-    echo "  git-stash (try)pop|apply|drop STASH_NAME"
-    echo "  git-stash list"
-    echo "  git-stash reflog (name filter)"
-    exit 1
+  echo "usage:"
+  echo "  git-stash push|find STASH_NAME"
+  echo "  git-stash (try)pop|apply|drop STASH_NAME"
+  echo "  git-stash list"
+  echo "  git-stash reflog (name filter)"
+  exit 1
 }
 
 # List command
 if [ "$1" == "list" ]; then
-    git stash list
-    exit 0
+  git stash list
+  exit 0
 # Reflog command, search the old stashes
 elif [ "$1" == "reflog" ]; then
-    shift
-    if [ -n "$1" ]; then
-        FILTER=--grep="$1"
-    fi
-    git fsck --unreachable | grep commit | cut -d" " -f3 | xargs git log --merges --no-walk $FILTER
-    exit 0
+  shift
+  if [ -n "$1" ]; then
+    FILTER=--grep="$1"
+  fi
+  git fsck --unreachable | grep commit | cut -d" " -f3 | xargs git log --merges --no-walk $FILTER
+  exit 0
 fi
 
 if [ -z "$1" ]; then
-    echo "E/No stash operation specified."
-    help
+  echo "E/No stash operation specified."
+  help
 fi
 OPERATION=$1
 shift
 
 if [ -z "$1" ]; then
-    echo "E/No stash name specified."
-    help
+  echo "E/No stash name specified."
+  help
 fi
 NAME=git-stash-$1
 shift
 ID=$(git stash list | grep "$NAME" | cut -d: -f1)
 
 case $OPERATION in
-    # Push a new stash
-    push)
-        if [ ! -z "$ID" ]; then
-            echo "E/Stash '$NAME' already exists."
-            help
-        fi
-        git stash save --include-untracked $NAME
-        ;;
-    # Apply stash and then drop it, exit 1 if the stash doesnt exist
-    pop)
-        if [ -z "$ID" ]; then
-            echo "E/Can't find stash '$NAME'"
-            help
-        fi
-        git stash apply $ID
-        git stash drop $ID
-        ;;
-    # Apply stash and then drop it, exit 0 and message if the stash doesnt exist
-    trypop)
-        if [ -z "$ID" ]; then
-            echo "I/trypop: no stash '$NAME', skipping."
-        else
-            git stash apply $ID
-            git stash drop $ID
-        fi
-        ;;
-    # Apply stash, exit 1 if the stash doesnt exist
-    apply)
-        if [ -z "$ID" ]; then
-            echo "E/Can't find stash '$NAME'"
-            help
-        fi
-        git stash apply $ID
-        ;;
-    # Apply stash, message if the stash doesnt exist
-    tryapply)
-        if [ -z "$ID" ]; then
-            echo "I/tryapply: no stash '$NAME', skipping."
-        else
-            git stash apply $ID
-        fi
-        ;;
-    # Drop the specified stash
-    drop)
-        if [ -z "$ID" ]; then
-            echo "E/Can't find stash '$NAME'"
-            help
-        fi
-        git stash drop $ID
-        ;;
-    # Drop the specified stash, message if the stash doesnt exist
-    trydrop)
-        if [ -z "$ID" ]; then
-            echo "I/trydrop: no stash '$NAME', skipping."
-        else
-            git stash drop $ID
-        fi
-        ;;
-    # Find the id of the specified stash
-    find)
-        echo $ID
-        ;;
-    *)
-        echo "E/Unknown git-stash operation '$OPERATION'"
-        help
-        ;;
+  # Push a new stash
+  push)
+    if [ ! -z "$ID" ]; then
+      echo "E/Stash '$NAME' already exists."
+      help
+    fi
+    git stash save --include-untracked $NAME
+    ;;
+  # Apply stash and then drop it, exit 1 if the stash doesnt exist
+  pop)
+    if [ -z "$ID" ]; then
+      echo "E/Can't find stash '$NAME'"
+      help
+    fi
+    git stash apply $ID
+    git stash drop $ID
+    ;;
+  # Apply stash and then drop it, exit 0 and message if the stash doesnt exist
+  trypop)
+    if [ -z "$ID" ]; then
+      echo "I/trypop: no stash '$NAME', skipping."
+    else
+      git stash apply $ID
+      git stash drop $ID
+    fi
+    ;;
+  # Apply stash, exit 1 if the stash doesnt exist
+  apply)
+    if [ -z "$ID" ]; then
+      echo "E/Can't find stash '$NAME'"
+      help
+    fi
+    git stash apply $ID
+    ;;
+  # Apply stash, message if the stash doesnt exist
+  tryapply)
+    if [ -z "$ID" ]; then
+      echo "I/tryapply: no stash '$NAME', skipping."
+    else
+      git stash apply $ID
+    fi
+    ;;
+  # Drop the specified stash
+  drop)
+    if [ -z "$ID" ]; then
+      echo "E/Can't find stash '$NAME'"
+      help
+    fi
+    git stash drop $ID
+    ;;
+  # Drop the specified stash, message if the stash doesnt exist
+  trydrop)
+    if [ -z "$ID" ]; then
+      echo "I/trydrop: no stash '$NAME', skipping."
+    else
+      git stash drop $ID
+    fi
+    ;;
+  # Find the id of the specified stash
+  find)
+    echo $ID
+    ;;
+  *)
+    echo "E/Unknown git-stash operation '$OPERATION'"
+    help
+    ;;
 esac
diff --git a/toolsets/repos/git-update b/toolsets/repos/git-update
--- a/toolsets/repos/git-update
+++ b/toolsets/repos/git-update
@@ -2,14 +2,14 @@
 . ham-bash-lib.sh
 
 usage() {
-    echo "usage: git-update (nofetch) BRANCH (ORIGIN_BRANCH)"
-    echo ""
-    echo "  Fetch all, checkout BRANCH then rebase on ORIGIN_BRANCH. Automatically abort the rebase if there are any conflict."
-    echo ""
-    echo "  BRANCH can be 'current_branch' or '.' to specify the branch currently checked-out."
-    echo "  ORIGIN_BRANCH is 'origin:BRANCH' if not specified."
-    echo ""
-    exit 1
+  echo "usage: git-update (nofetch) BRANCH (ORIGIN_BRANCH)"
+  echo ""
+  echo "  Fetch all, checkout BRANCH then rebase on ORIGIN_BRANCH. Automatically abort the rebase if there are any conflict."
+  echo ""
+  echo "  BRANCH can be 'current_branch' or '.' to specify the branch currently checked-out."
+  echo "  ORIGIN_BRANCH is 'origin:BRANCH' if not specified."
+  echo ""
+  exit 1
 }
 
 REPO_NAME=$(basename $(git rev-parse --show-toplevel))
@@ -24,37 +24,44 @@ if [ -z "$1" ]; then
   echo "E/BRANCH not specified."
   usage
 fi
-BRANCH=`git-get-branch-name "$1"`
+BRANCH=$(git-get-branch-name "$1")
 shift
 
 if [ -z "$1" ]; then
-  ORIGIN_BRANCH=`git-get-branch-name "origin:$BRANCH"`
+  ORIGIN_BRANCH=$(git-get-branch-name "origin:$BRANCH")
 else
-  ORIGIN_BRANCH=`git-get-branch-name "$1"`
+  ORIGIN_BRANCH=$(git-get-branch-name "$1")
   shift
 fi
 log_info "Updating '$REPO_NAME' by rebasing '$BRANCH' onto '$ORIGIN_BRANCH'."
 
 if [ "$DO_FETCH" = "1" ]; then
-  (set -x ;
-   git fetch --prune --all)
+  (
+    set -x
+    git fetch --prune --all
+  )
 fi
 
-(set -x ;
- git checkout "$BRANCH" ;
- git-rebase "$ORIGIN_BRANCH")
+(
+  set -x
+  git checkout "$BRANCH"
+  git-rebase "$ORIGIN_BRANCH"
+)
 
 function in_rebase() {
-    g=$(git rev-parse --git-dir)
-    if [ -d "$g/rebase-merge" ] || [ -d "$g/rebase-apply" ]; then
-        return 0
-    else
-        return 1
-    fi
+  g=$(git rev-parse --git-dir)
+  if [ -d "$g/rebase-merge" ] || [ -d "$g/rebase-apply" ]; then
+    return 0
+  else
+    return 1
+  fi
 }
 if in_rebase; then
   log_error "Repo '$REPO_NAME' update failed, rebase aborted because of conflicts."
-  (set -x ; git rebase --abort)
+  (
+    set -x
+    git rebase --abort
+  )
   exit 1
 else
   log_success "Repo '$REPO_NAME' update done, rebase succeeded."
diff --git a/toolsets/solana/solana-install b/toolsets/solana/solana-install
--- a/toolsets/solana/solana-install
+++ b/toolsets/solana/solana-install
@@ -17,14 +17,14 @@ SOLANA_DOWNLOAD_ROOT=https://release.solana.com
 
 { # this ensures the entire script is downloaded #
 
-if [ -z "$SOLANA_DOWNLOAD_ROOT" ]; then
+  if [ -z "$SOLANA_DOWNLOAD_ROOT" ]; then
     SOLANA_DOWNLOAD_ROOT="https://github.com/solana-labs/solana/releases/download/"
-fi
-GH_LATEST_RELEASE="https://api.github.com/repos/solana-labs/solana/releases/latest"
+  fi
+  GH_LATEST_RELEASE="https://api.github.com/repos/solana-labs/solana/releases/latest"
 
-set -e
+  set -e
 
-usage() {
+  usage() {
     cat 1>&2 <<EOF
 solana-install-init
 initializes a new installation
@@ -41,9 +41,9 @@ OPTIONS:
     -u, --url <URL>          JSON RPC URL for the solana cluster
     -p, --pubkey <PUBKEY>    Public key of the update manifest
 EOF
-}
+  }
 
-main() {
+  main() {
     downloader --check
     need_cmd uname
     need_cmd mktemp
@@ -55,12 +55,11 @@ main() {
 
     for arg in "$@"; do
       case "$arg" in
-        -h|--help)
+        -h | --help)
           usage
           exit 0
           ;;
-        *)
-          ;;
+        *) ;;
       esac
     done
 
@@ -68,18 +67,18 @@ main() {
     _cputype="$(uname -m)"
 
     case "$_ostype" in
-    Linux)
-      _ostype=unknown-linux-gnu
-      ;;
-    Darwin)
-      if [[ $_cputype = arm64 ]]; then
-        _cputype=aarch64
-      fi
-      _ostype=apple-darwin
-      ;;
-    *)
-      err "machine architecture is currently unsupported"
-      ;;
+      Linux)
+        _ostype=unknown-linux-gnu
+        ;;
+      Darwin)
+        if [[ $_cputype = arm64 ]]; then
+          _cputype=aarch64
+        fi
+        _ostype=apple-darwin
+        ;;
+      *)
+        err "machine architecture is currently unsupported"
+        ;;
     esac
     TARGET="${_cputype}-${_ostype}"
 
@@ -94,9 +93,9 @@ main() {
       release_file="$temp_dir/release"
       printf 'looking for latest release\n' 1>&2
       ensure downloader "$GH_LATEST_RELEASE" "$release_file"
-      release=$(\
-        grep -m 1 \"tag_name\": "$release_file" \
-        | sed -ne 's/^ *"tag_name": "\([^"]*\)",$/\1/p' \
+      release=$(
+        grep -m 1 \"tag_name\": "$release_file" |
+          sed -ne 's/^ *"tag_name": "\([^"]*\)",$/\1/p'
       )
       if [ -z "$release" ]; then
         err 'Unable to figure latest release'
@@ -117,9 +116,9 @@ main() {
     ensure downloader "$download_url" "$solana_install_init"
     ensure chmod u+x "$solana_install_init"
     if [ ! -x "$solana_install_init" ]; then
-        printf '%s\n' "Cannot execute $solana_install_init (likely because of mounting /tmp as noexec)." 1>&2
-        printf '%s\n' "Please copy the file to a location where you can execute binaries and run ./solana-install-init." 1>&2
-        exit 1
+      printf '%s\n' "Cannot execute $solana_install_init (likely because of mounting /tmp as noexec)." 1>&2
+      printf '%s\n' "Please copy the file to a location where you can execute binaries and run ./solana-install-init." 1>&2
+      exit 1
     fi
 
     set -x
@@ -130,61 +129,61 @@ main() {
     ignore rm -rf "$temp_dir"
 
     return "$retval"
-}
+  }
 
-err() {
+  err() {
     printf 'solana-install-init: %s\n' "$1" >&2
     exit 1
-}
+  }
 
-need_cmd() {
+  need_cmd() {
     if ! check_cmd "$1"; then
-        err "need '$1' (command not found)"
+      err "need '$1' (command not found)"
     fi
-}
+  }
 
-check_cmd() {
-    command -v "$1" > /dev/null 2>&1
-}
+  check_cmd() {
+    command -v "$1" >/dev/null 2>&1
+  }
 
-# Run a command that should never fail. If the command fails execution
-# will immediately terminate with an error showing the failing
-# command.
-ensure() {
+  # Run a command that should never fail. If the command fails execution
+  # will immediately terminate with an error showing the failing
+  # command.
+  ensure() {
     if ! "$@"; then
       err "command failed: $*"
     fi
-}
+  }
 
-# This is just for indicating that commands' results are being
-# intentionally ignored. Usually, because it's being executed
-# as part of error handling.
-ignore() {
+  # This is just for indicating that commands' results are being
+  # intentionally ignored. Usually, because it's being executed
+  # as part of error handling.
+  ignore() {
     "$@"
-}
+  }
 
-# This wraps curl or wget. Try curl first, if not installed,
-# use wget instead.
-downloader() {
+  # This wraps curl or wget. Try curl first, if not installed,
+  # use wget instead.
+  downloader() {
     if check_cmd curl; then
-        program=curl
+      program=curl
     elif check_cmd wget; then
-        program=wget
+      program=wget
     else
-        program='curl or wget' # to be used in error message of need_cmd
+      program='curl or wget' # to be used in error message of need_cmd
     fi
 
     if [ "$1" = --check ]; then
-        need_cmd "$program"
+      need_cmd "$program"
     elif [ "$program" = curl ]; then
-        curl -sSfL "$1" -o "$2"
+      curl -sSfL "$1" -o "$2"
     elif [ "$program" = wget ]; then
-        wget "$1" -O "$2"
+      wget "$1" -O "$2"
     else
-        err "Unknown downloader"   # should not reach here
+      err "Unknown downloader" # should not reach here
     fi
-}
+  }
 
-main "$@"
+  main "$@"
 
 } # this ensures the entire script is downloaded #
diff --git a/toolsets/svn/svn-ignore-update b/toolsets/svn/svn-ignore-update
--- a/toolsets/svn/svn-ignore-update
+++ b/toolsets/svn/svn-ignore-update
@@ -1,39 +1,39 @@
 #!/bin/bash
 usage() {
-    echo "usage: svn-ignore-update directory"
-    echo "  Apply the _svnignore_r & _svnignore_this in the specified directory."
-    echo ""
-    echo "  _svnignore_r contains the patterns that must be applied to all the subdirectories."
-    echo "  _svnignore_this contains the patterns that must be applied only to specified directory."
-    echo ""
-    echo "  Not that _svnignore_this overrides completely _svnignore_r for the specified directory,"
-    echo "  so patterns must be duplicated in both ignore list if required."
-    echo ""
-    if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
-        # sourced...
-        return 1
-    else
-        # regular call
-        exit 1
-    fi
+  echo "usage: svn-ignore-update directory"
+  echo "  Apply the _svnignore_r & _svnignore_this in the specified directory."
+  echo ""
+  echo "  _svnignore_r contains the patterns that must be applied to all the subdirectories."
+  echo "  _svnignore_this contains the patterns that must be applied only to specified directory."
+  echo ""
+  echo "  Not that _svnignore_this overrides completely _svnignore_r for the specified directory,"
+  echo "  so patterns must be duplicated in both ignore list if required."
+  echo ""
+  if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
+    # sourced...
+    return 1
+  else
+    # regular call
+    exit 1
+  fi
 }
 
 DEST="$1"
 if [ -z "$DEST" ]; then
-    echo "E/SVN folder not specified."
-    usage
+  echo "E/SVN folder not specified."
+  usage
 fi
 
 SVN_IGNORE_R="$DEST/_svnignore_r"
 if [ ! -e "$SVN_IGNORE_R" ]; then
-    echo "E/'$SVN_IGNORE_R' not found"
-    usage
+  echo "E/'$SVN_IGNORE_R' not found"
+  usage
 fi
 
 SVN_IGNORE_THIS="$DEST/_svnignore_this"
 if [ ! -e "$SVN_IGNORE_THIS" ]; then
-    echo "E/'$SVN_IGNORE_THIS' not found"
-    usage
+  echo "E/'$SVN_IGNORE_THIS' not found"
+  usage
 fi
 
 echo "I/Apply _svnignore_r & _svnignore_this"
diff --git a/toolsets/xslt_tools/xslt_tools-xslt1 b/toolsets/xslt_tools/xslt_tools-xslt1
--- a/toolsets/xslt_tools/xslt_tools-xslt1
+++ b/toolsets/xslt_tools/xslt_tools-xslt1
@@ -1,15 +1,15 @@
 #!/bin/bash
 . ham-bash-lib.sh
 if [ -e "${1}" ]; then
-    XSLTPATH="$1"
+  XSLTPATH="$1"
 else
-    echo "Can't find XSLT: $1"
-    exit 1
+  echo "Can't find XSLT: $1"
+  exit 1
 fi
 if [ -z "$3" ]; then
-    OUTPUT=
+  OUTPUT=
 else
-    OUTPUT="--output \"$3\""
+  OUTPUT="--output \"$3\""
 fi
 # echo "# XSLT1: $2 -> '$(basename "${XSLTPATH}")' -> $3"
 xslt_tools-xsltproc "$OUTPUT" "$XSLTPATH" "$2"
